In [42]:
# pip install pandas openpyxl

In [1]:
import pandas as pd
import numpy as np

# OCIO

In [44]:
ocio = pd.read_excel("ocio.xlsx")
ocio

c:\Users\cchia\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Nombre,Descripción,Tipo de Plantilla,Localidad,Calidad,URL del Icono de Calidad,Descripción del Icono de Calidad,Accesible,URL del Icono de Accesibilidad,Descripción del Icono de Accesibilidad,...,Código provincia,País,Código país,Teléfono.1,Correo electrónico,Página web,URL amigable,URL física,XML datos,XML metadatos
0,Aquarium de San Sebastián,El Aquarium de San Sebastián está dotado de un...,Aquariums,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/aquariums/aqua...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
1,Plaza de Toros de Vista Alegre,Plaza de primera categoría inaugurada en 1962 ...,Plazas de toros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/plaza-de-toros...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
2,Plaza de Toros de Orduña,Plaza de tercera categoría con capacidad para ...,Plazas de toros,Urduña/Orduña,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/plaza-de-toros...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
3,Plaza de Toros de Azpeitia,Plaza de tercera categoría con capacidad para ...,Plazas de toros,Azpeitia,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/plaza-de-toros...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
4,Plaza de Toros de Illumbe,La Plaza de Toros de Illumbe fue inaugurada en...,Plazas de toros,Donostia / San Sebastián,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/plaza-de-toros...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
5,Plaza de Toros de Eibar,Plaza de tercera categoría de titularidad muni...,Plazas de toros,Eibar,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/plaza-de-toros...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
6,Plaza de Toros de Tolosa,Plaza de tercera categoría con 5.500 localidad...,Plazas de toros,Tolosa,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/plaza-de-toros...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
7,Parque de Atracciones del Monte Igueldo,Está situado en un alto al que podemos acceder...,Parques temáticos y de atracciones,Donostia / San Sebastián,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/parques-temati...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
8,Casino Kursaal,El Gran Kursaal se encuentra en el centro de D...,Casinos,Donostia / San Sebastián,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/casinos/casino...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
9,Luckia Casino Bilbao,Luckia Casino Bilbao es un espacio de ocio sit...,Casinos,Bilbao,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/casinos/gran-c...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
10,Plaza de Toros de Vitoria,La primera plaza de toros de Vitoria estuvo en...,Plazas de toros,Vitoria-Gasteiz,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/plaza-de-toros...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
11,De pintxos por el Casco Viejo de Bilbao,Es la zona de más tradición de la capital vizc...,Zonas de bares,Bilbao,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/bares-pintxos/...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
12,De pintxos por el centro Vitoria-Gasteiz,La gastronomía es uno de los grandes placeres ...,Zonas de bares,Vitoria-Gasteiz,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/bares-pintxos/...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
13,De pintxos por el Casco Viejo de Vitoria-Gasteiz,Las calles empedradas del Casco Viejo de Vitor...,Zonas de bares,Vitoria-Gasteiz,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/bares-pintxos/...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
14,De pintxos por el Ensanche de Bilbao,"El Ensanche es la arteria comercial de Bilbao,...",Zonas de bares,Bilbao,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/bares-pintxos/...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
15,"De pintxos por Indautxu, Bilbao",Es una de las áreas bilbaínas que combina el a...,Zonas de bares,Bilbao,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/bares-pintxos/...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
16,De pintxos por la Gran Vía de Bilbao,El final de la Gran Vía y las calles aledañas ...,Zonas de bares,Bilbao,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/bares-pintxos/...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
17,De pintxos por la Parte Vieja de San Sebastián,Es el templo de los pintxos tanto para las cua...,Zonas de bares,Donostia / San Sebastián,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/bares-pintxos/...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
18,De pintxos por la zona centro de San Sebastián,"Es la zona elegante de San Sebastián, entre La...",Zonas de bares,Donostia / San Sebastián,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/bares-pintxos/...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
19,"De pintxos por Ondarreta, San Sebastián","Frente a la playa de Ondarreta, en el lado izq...",Zonas de bares,Donostia / San Sebastián,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/bares-pintxos/...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
20,"De pintxos por Gros, San Sebastián",El Kursaal y la Playa de la Zurriola son las p...,Zonas de bares,Donostia / San Sebastián,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/bares-pintxos/...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
21,BBK Karpin Fauna,Hubo una época en la que los dinosaurios domin...,Parques temáticos y de atracciones,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/parques-temati...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
22,Izenaduba Basoa,"¡Izenaduba es un bosque mágico! Olentzero, los...",Parques temáticos y de atracciones,Mungia,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/parques-temati...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
23,Basondo,Basondo es un refugio para la fauna silvestre ...,Parques temáticos y de atracciones,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/parques-temati...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
24,Mendexa Abentura Park,"Diseñado para el disfrute de niños y adultos, ...",Parques temáticos y de atracciones,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/parques-temati...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
25,Bizkaia Park Abentura,"Piscinas de bolas, hinchables, colchonetas, c...",Parques temáticos y de atracciones,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/parques-temati...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
26,Pepe por Dios,NaN,Locales de noche,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/locales-de-noc...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
27,El Balcón de la Lola,"No obstante, en El balcón de la Lola se juntan...",Locales de noche,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/locales-de-noc...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...
28,Bako kluba,NaN,Locales de noche,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/locales-de-noc...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/k_ocio...,https://turismoa.euskadi.eus/contenidos/k_ocio...

No son planes para nuestro público objetivo... fuera.

# MUSEOS

In [45]:
museos2 = pd.read_excel("xls0003477_c.xlsx")
museos2

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Museos y colecciones de la C.A. de Euskadi seg...,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,C.A. de Euskadi,Araba/Álava,Bizkaia,Gipuzkoa
4,Nº de museos y colecciones (participantes en l...,64,10,25,29
5,Número de visitantes,2951350,216026,1829253,906071
6,Personal,794,81,322,391
7,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN
9,Fuente: Gobierno Vasco. Departamento de Cultur...,NaN,NaN,NaN,NaN

Este excel solo nos da totales de visitantes y personal. No nos interesa.

In [46]:
museos3 = pd.read_csv("22tef6.csv", sep=";")
museos3

,elkar,inkes,lurral,tfno,P0A,P0B,p01,p02,p03,p0401,...,p35,p36,p37,p38,p39,p40,p41,p42,p43,wt
0,EK22022OCT204072000095,4072,1,2,3,999,2,45,1,2,...,3,5,2,3,4,6,0,1,4,",388338093031412"
1,EK22022OCT204072000302,4072,1,1,3,59,2,78,5,14,...,5,1,3,1,4,1,6,4,1,",558820521856143"
2,EK22022OCT205043000094,6509,1,1,3,2,1,26,1,19,...,2,3,3,1,4,6,0,4,1,",171957285121412"
3,EK22022OCT205043000186,6511,1,2,3,59,1,34,1,7,...,1,5,2,1,4,6,0,2,4,",388338093031412"
4,EK22022OCT205043000223,5044,1,2,3,59,1,44,1,7,...,4,3,2,1,4,2,1,2,4,",516265600633546"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1309,EK22022OCT296624001544,6624,3,1,1,69,1,79,5,7,...,1,2,3,3,4,1,11,4,2,"2,11652918615898"
1310,EK22022OCT296624001559,6623,3,1,3,69,1,88,5,12,...,5,4,2,5,4,1,8,4,1,"2,11652918615898"
1311,EK22022OCT296624001608,6624,3,1,3,69,1,65,5,7,...,1,5,2,3,4,2,8,4,1,",751418487130269"
1312,EK22022OCT297002001180,7002,3,1,3,69,1,76,5,19,...,5,5,1,3,4,1,7,4,1,",751418487130269"
1313,EK22022OCT297002001251,5045,3,1,3,69,2,66,5,99,...,4,4,2,3,4,2,0,4,1,"2,11652918615898"

Son datos sobre todo de convivencia y diversidad; solo hay una pregunta con respecto a museos (visita en el último año). Fuera.

In [47]:
museos = pd.read_excel("museos.xlsx")
museos

c:\Users\cchia\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Nombre,Descripción,Tipo de Plantilla,Localidad,Calidad,URL del Icono de Calidad,Descripción del Icono de Calidad,Accesible,URL del Icono de Accesibilidad,Descripción del Icono de Accesibilidad,...,Código provincia,País,Código país,Teléfono.1,Correo electrónico,Página web,URL amigable,URL física,XML datos,XML metadatos
0,Museo Bibat,Ubicado en el Casco Antiguo de Vitoria-Gasteiz...,Auditorios; Museos; Galerías de arte y salas d...,Vitoria-Gasteiz,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-b...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
1,Museo de Faroles de la Cofradía de la Virgen B...,Este original museo alberga las 267 piezas de ...,Auditorios; Museos; Galerías de arte y salas d...,Vitoria-Gasteiz,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
2,Museo de Ciencias Naturales de Álava,El Museo de Ciencias Naturales de Álava cuenta...,Auditorios; Museos; Galerías de arte y salas d...,Vitoria-Gasteiz,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
3,Artium museoa,El/la visitante podrá encontrar en exposición ...,Auditorios; Museos; Galerías de arte y salas d...,Vitoria-Gasteiz,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/artium-...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
4,Museo de Armería,El Museo de Armería ofrece al visitante una ex...,Auditorios; Museos; Galerías de arte y salas d...,Vitoria-Gasteiz,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,Arkeologi Museoa,"El museo de arqueología Arkeologi Museoa, inau...",Auditorios; Museos; Galerías de arte y salas d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/arkeolo...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
147,Museo Orduña Hiria Museoa,El museo etnográfico y cultural de Orduña está...,Auditorios; Museos; Galerías de arte y salas d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-o...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
148,BBK Klima,BBK Klima,Auditorios; Museos; Galerías de arte y salas d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/bbk-kli...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
149,Ekoetxea Añana-Sobron,Ekoetxea Añana Sobron nos ayuda a descubrir la...,Auditorios; Museos; Galerías de arte y salas d...,Sobrón,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/ekoetxe...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
150,Mendietxe Museoa,"El Mendietxe Museoa, situado en Azpeitia, es u...",Auditorios; Museos; Galerías de arte y salas d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/mendiet...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...

In [48]:
museos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 51 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Nombre                                  151 non-null    object
 1   Descripción                             151 non-null    object
 2   Tipo de Plantilla                       151 non-null    object
 3   Localidad                               114 non-null    object
 4   Calidad                                 0 non-null      float64
 5   URL del Icono de Calidad                0 non-null      float64
 6   Descripción del Icono de Calidad        0 non-null      float64
 7   Accesible                               0 non-null      float64
 8   URL del Icono de Accesibilidad          0 non-null      float64
 9   Descripción del Icono de Accesibilidad  0 non-null      float64
 10  Teléfono                                144 non-null    object
 11  Dirección                               149 non-null    object
 12  Marcas                                  151 non-null    object
 13  Diversidad functional física            151 non-null    object
 14  Diversidad functional visual            151 non-null    object
 15  Diversidad functional auditiva          151 non-null    object
 16  Diversidad functional intelectual       151 non-null    object
 17  Diversidad functional orgánica          151 non-null    object
 18  Buenas prácticas                        47 non-null     float64
 19  Email                                   137 non-null    object
 20  WEB                                     134 non-null    object
 21  Importancia                             0 non-null      float64
 22  Sala de Reuniones                       0 non-null      float64
 23  Club de Producto                        9 non-null      float64
 24  Visita Guiada                           97 non-null     float64
 25  Capacidad                               151 non-null    int64
 26  Tienda                                  54 non-null     float64
 27  Actividades Gastronómicas               0 non-null      float64
 28  Surfing                                 0 non-null      float64
 29  Postal Code                             128 non-null    float64
 30  Tipo de Cultura                         117 non-null    object
 31  Subtipo de Cultura                      0 non-null      float64
 32  Coordenadas GPS                         150 non-null    object
 33  LATWGS84                                150 non-null    float64
 34  LONWGS84                                150 non-null    float64
 35  Nombre lugar                            0 non-null      float64
 36  Dirección.1                             0 non-null      float64
 37  Municipio                               151 non-null    object
 38  Código municipio                        151 non-null    int64
 39  Código postal                           0 non-null      float64
 40  Provincia                               151 non-null    object
 41  Código provincia                        151 non-null    int64
 42  País                                    151 non-null    object
 43  Código país                             151 non-null    int64
 44  Teléfono.1                              0 non-null      float64
 45  Correo electrónico                      0 non-null      float64
 46  Página web                              0 non-null      float64
 47  URL amigable                            151 non-null    object
 48  URL física                              151 non-null    object
 49  XML datos                               151 non-null    object
 50  XML metadatos                           151 non-null    object
dtypes: float64(24), int64(4), object(23)
memory usage: 60.3+ KB

In [49]:
museos.columns

Index(['Nombre', 'Descripción', 'Tipo de Plantilla', 'Localidad', 'Calidad',
       'URL del Icono de Calidad', 'Descripción del Icono de Calidad',
       'Accesible', 'URL del Icono de Accesibilidad',
       'Descripción del Icono de Accesibilidad', 'Teléfono', 'Dirección',
       'Marcas', 'Diversidad functional física ',
       'Diversidad functional visual ', 'Diversidad functional auditiva ',
       'Diversidad functional intelectual ', 'Diversidad functional orgánica ',
       'Buenas prácticas ', 'Email', 'WEB', 'Importancia', 'Sala de Reuniones',
       'Club de Producto', 'Visita Guiada', 'Capacidad', 'Tienda',
       'Actividades Gastronómicas', 'Surfing', 'Postal Code',
       'Tipo de Cultura', 'Subtipo de Cultura', 'Coordenadas GPS', 'LATWGS84',
       'LONWGS84', 'Nombre lugar', 'Dirección.1', 'Municipio',
       'Código municipio', 'Código postal', 'Provincia', 'Código provincia',
       'País', 'Código país', 'Teléfono.1', 'Correo electrónico', 'Página web',
       'URL amigable', 'URL física', 'XML datos', 'XML metadatos'],
      dtype='object')

In [50]:
museos_limpio = museos.dropna(how='all', axis=1)
museos_limpio.drop(['Diversidad functional visual ', 
                    'Diversidad functional auditiva ',
                    'Diversidad functional intelectual ',
                    'Diversidad functional física ', 
                    'Diversidad functional orgánica '], 
                   axis=1, 
                   inplace=True)
museos_limpio

C:\Users\cchia\AppData\Local\Temp\ipykernel_15832\2740806479.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  museos_limpio.drop(['Diversidad functional visual ',

,Nombre,Descripción,Tipo de Plantilla,Localidad,Teléfono,Dirección,Marcas,Buenas prácticas,Email,WEB,...,Municipio,Código municipio,Provincia,Código provincia,País,Código país,URL amigable,URL física,XML datos,XML metadatos
0,Museo Bibat,Ubicado en el Casco Antiguo de Vitoria-Gasteiz...,Auditorios; Museos; Galerías de arte y salas d...,Vitoria-Gasteiz,945 203 700,"Cuchillería, 54. Junto al Palacio de Bendaña.",Vitoria-Gasteiz,NaN,bibat@araba.eus,https://fourniermuseoabibat.eus/es/inicio,...,Vitoria-Gasteiz,59,Araba/Álava,1,España,108,https://turismoa.euskadi.eus/es/museos/museo-b...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
1,Museo de Faroles de la Cofradía de la Virgen B...,Este original museo alberga las 267 piezas de ...,Auditorios; Museos; Galerías de arte y salas d...,Vitoria-Gasteiz,945 277 077,"Zapatería, 33",Vitoria-Gasteiz,NaN,info@cofradiavirgenblanca.com,http://www.cofradiavirgenblanca.com/,...,Vitoria-Gasteiz,59,Araba/Álava,1,España,108,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
2,Museo de Ciencias Naturales de Álava,El Museo de Ciencias Naturales de Álava cuenta...,Auditorios; Museos; Galerías de arte y salas d...,Vitoria-Gasteiz,945 181 924,"Fundadora de las Siervas de Jesús, 24",Vitoria-Gasteiz,NaN,mcna@araba.eus,NaN,...,Vitoria-Gasteiz,59,Araba/Álava,1,España,108,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
3,Artium museoa,El/la visitante podrá encontrar en exposición ...,Auditorios; Museos; Galerías de arte y salas d...,Vitoria-Gasteiz,945 209 020,"Francia, 24",Vitoria-Gasteiz,1.0,museo@artium.eus,https://www.artium.eus/es/,...,Vitoria-Gasteiz,59,Araba/Álava,1,España,108,https://turismoa.euskadi.eus/es/museos/artium-...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
4,Museo de Armería,El Museo de Armería ofrece al visitante una ex...,Auditorios; Museos; Galerías de arte y salas d...,Vitoria-Gasteiz,945 181 925,"Paseo de Fray Francisco de Vitoria, 3",Vitoria-Gasteiz,NaN,museoarmeria@araba.eus,NaN,...,Vitoria-Gasteiz,59,Araba/Álava,1,España,108,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,Arkeologi Museoa,"El museo de arqueología Arkeologi Museoa, inau...",Auditorios; Museos; Galerías de arte y salas d...,NaN,944 040 990,"Calzada de Mallona, 2",Bilbao,NaN,arkeologimuseoa@bizkaia.eus,NaN,...,Bilbao,20,Bizkaia,48,España,108,https://turismoa.euskadi.eus/es/museos/arkeolo...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
147,Museo Orduña Hiria Museoa,El museo etnográfico y cultural de Orduña está...,Auditorios; Museos; Galerías de arte y salas d...,NaN,635 751 436,"Andra Mari plaza, 1",Montes y Valles vascos,NaN,contacto@ordunahiria.org,https://www.ordunahiria.org/,...,Urduña/Orduña,74,Bizkaia,48,España,108,https://turismoa.euskadi.eus/es/museos/museo-o...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
148,BBK Klima,BBK Klima,Auditorios; Museos; Galerías de arte y salas d...,NaN,NaN,"Axpe Auzoa, 121",Costa Vasca,NaN,NaN,https://www.bbk.eus/bbk-klima/,...,Busturia,21,Bizkaia,48,España,108,https://turismoa.euskadi.eus/es/museos/bbk-kli...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
149,Ekoetxea Añana-Sobron,Ekoetxea Añana Sobron nos ayuda a descubrir la...,Auditorios; Museos; Galerías de arte y salas d...,Sobrón,945 359 235,"La Presa, 2",Montes y Valles vascos,NaN,info.sobron@ekoetxea.eus,https://ekoetxea.eus/es/sobron/,...,Lantarón,902,Araba/Álava,1,España,108,https://turismoa.euskadi.eus/es/museos/ekoetxe...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
150,Mendietxe Museoa,"El Mendietxe Museoa, situado en Azpeitia, es u...",Auditorios; Museos; Galerías de arte y salas d...,NaN,601 925 006,"Loiolako Inazio hiribidea, 20",Montes y Valles vascos,NaN,mendiarenetxea@gmail.com,https://mendietxemuseoa.eus/,...,Azpeitia,18,Gipuzkoa,20,España,108,https://turismoa.euskadi.eus/es/museos/mendiet...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...

In [57]:
museos["Tipo de Cultura"].value_counts()

Tipo de Cultura
Otros                 29
Historia              19
Ciencias Naturales    17
Arte                  15
Etnografía            14
Marítimo               9
Gastronomía            8
Religión               5
Artesanía              1
Name: count, dtype: int64

In [60]:
museos[museos["Tipo de Cultura"] == "Etnografía"]

,Nombre,Descripción,Tipo de Plantilla,Localidad,Calidad,URL del Icono de Calidad,Descripción del Icono de Calidad,Accesible,URL del Icono de Accesibilidad,Descripción del Icono de Accesibilidad,...,Código provincia,País,Código país,Teléfono.1,Correo electrónico,Página web,URL amigable,URL física,XML datos,XML metadatos
10,Museo Etnográfico Usatxi de Pipaón,A través del Museo Etnográfico 'Usatxi' de Pip...,Auditorios; Museos; Galerías de arte y salas d...,Pipaon,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-e...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
11,Museo Etnográfico de Artziniega,"Creado en 1984 y ampliado en 2004, acoge una a...",Auditorios; Museos; Galerías de arte y salas d...,Artziniega,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-e...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
14,Museo Etnográfico de Oyón-Oion,El Museo Etnográfico de Oyón-Oion describe la ...,Auditorios; Museos; Galerías de arte y salas d...,Oyón-Oion,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-e...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
20,Larraulgo Ekomuseoa,"Larraulgo Ekomuseoa nació en 2009, y pretende ...",Auditorios; Museos; Galerías de arte y salas d...,Larraul,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/larraul...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
29,Museo-Territorio Lenbur,El proyecto Lenbur (Legazpi Natura eta Burdina...,Auditorios; Museos; Galerías de arte y salas d...,Legazpi,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-t...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
30,"D'elikatuz, Centro de interpretación del Goierri",El Centro de interpretación del Goierri muestr...,Auditorios; Museos; Galerías de arte y salas d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/delikat...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
32,Museo Ibarraundi,"En 1986, en un local situado en el mismo Ayunt...",Auditorios; Museos; Galerías de arte y salas d...,Eskoriatza,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-i...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
37,Caserío Museo Igartubeiti,Es un exponente de la arquitectura en madera d...,Auditorios; Museos; Galerías de arte y salas d...,Ezkio,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/caserio...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
50,Museo de Orozko,"Gracias a su exposición permanente, puesto que...",Auditorios; Museos; Galerías de arte y salas d...,Zubiaur,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
58,Parque Cultural de Zerain,El Museo Etnográfico alberga más de 200 elemen...,Auditorios; Museos; Galerías de arte y salas d...,Zerain,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/parque-...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
61,Museo Vasco. Museo Etnográfico e Histórico Vasco,TEMPORALMENTE CERRADOEl Museo Vasco muestra la...,Auditorios; Museos; Galerías de arte y salas d...,Bilbao,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-v...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
72,Ecomuseo del Pastoreo,"El Ecomuseo del Pastoreo, ubicado en un caserí...",Auditorios; Museos; Galerías de arte y salas d...,Telleriarte,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/ecomuse...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
75,Casa Ardixarra,Además de ser una de las casas más antiguas de...,Auditorios; Museos; Galerías de arte y salas d...,Segura,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/casa-ar...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
76,Museo Romano Oiasso,"Es, además, un espacio de desarrollo de activi...",Auditorios; Museos; Galerías de arte y salas d...,Irun,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-r...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...

In [59]:
museos[museos["Tipo de Cultura"] == "Otros"]

,Nombre,Descripción,Tipo de Plantilla,Localidad,Calidad,URL del Icono de Calidad,Descripción del Icono de Calidad,Accesible,URL del Icono de Accesibilidad,Descripción del Icono de Accesibilidad,...,Código provincia,País,Código país,Teléfono.1,Correo electrónico,Página web,URL amigable,URL física,XML datos,XML metadatos
0,Museo Bibat,Ubicado en el Casco Antiguo de Vitoria-Gasteiz...,Auditorios; Museos; Galerías de arte y salas d...,Vitoria-Gasteiz,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-b...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
1,Museo de Faroles de la Cofradía de la Virgen B...,Este original museo alberga las 267 piezas de ...,Auditorios; Museos; Galerías de arte y salas d...,Vitoria-Gasteiz,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
4,Museo de Armería,El Museo de Armería ofrece al visitante una ex...,Auditorios; Museos; Galerías de arte y salas d...,Vitoria-Gasteiz,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
9,Museo de la Policía Vasca,Los fondos que componen la exposición permanen...,Auditorios; Museos; Galerías de arte y salas d...,Arkauti/Arcaute | Arkauti / Arcaute,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
21,Museum Cemento Rezola,Museum Cemento Rezola está dedicado en a la hi...,Auditorios; Museos; Galerías de arte y salas d...,Donostia / San Sebastián,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museum-...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
28,Museo Salino,El Museo de la Sal de Leintz Gatzaga muestra l...,Auditorios; Museos; Galerías de arte y salas d...,Leintz-Gatzaga,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
33,Museo Vasco del Ferrocarril,"Locomotoras de vapor, tranvías urbanos, vagone...",Auditorios; Museos; Galerías de arte y salas d...,Azpeitia,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-v...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
42,Museo de la Máquina-Herramienta,El Museo de la Máquina-Herramienta quiere home...,Auditorios; Museos; Galerías de arte y salas d...,Elgoibar,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
44,Ecomuseo del Caserío Vasco,El Ecomuseo o Euskal Baserria se sitúa en un c...,Auditorios; Museos; Galerías de arte y salas d...,Herriko Plaza,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/ecomuse...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
45,Museo Taurino de Bilbao,El Museo Taurino repasa la historia de la taur...,Auditorios; Museos; Galerías de arte y salas d...,Bilbao,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-t...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
51,Museo de la Minería del País Vasco,El Museo de la Minería del País Vasco está ded...,Auditorios; Museos; Galerías de arte y salas d...,Gallarta,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
53,Ferrería de El Pobal,"El conjunto visitable, emplazado en un bello m...",Auditorios; Museos; Galerías de arte y salas d...,La Rigada | Diseminado,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/ferreri...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
60,Soinuenea,"Asimismo, tiene una biblioteca de más de 5.800...",Auditorios; Museos; Galerías de arte y salas d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/soinuen...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
64,Servicio de Patrimonio Histórico-Artístico y A...,Se debe llamar a este servicio para concertar ...,Auditorios; Museos; Galerías de arte y salas d...,Vitoria-Gasteiz,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/sede-ce...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
68,Museo de coches antiguos y clásicos (Torre de ...,"El castillo de Concejuelo, majestuosa fortalez...",Auditorios; Museos; Galerías de arte y salas d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
69,La Encartada Fabrika Museoa,"Situada a las afueras de Balmaseda, en la ribe...",Auditorios; Museos; Galerías de arte y salas d...,Peñueco | Diseminado,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/boinas-...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
70,Museo del Licor Manuel Acha,El primer Museo del Licor de Euskadi recorre l...,Auditorios; Museos; Galerías de arte y salas d...,Amurrio,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
74,Museo del Hierro Vasco,"Además, muestra los elementos originales de la...",Auditorios; Museos; Galerías de arte y salas d...,Telleriarte,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
80,TOPIC. Centro Internacional del Títere de Tolosa,Se trata del único centro de toda Europa dedic...,Auditorios; Museos; Galerías de arte y salas d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/topic-c...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
81,Museo de la Industria Armera,La ciudad de Eibar dispone de un museo dedicad...,Auditorios; Museos; Galerías de arte y salas d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
84,AZKUNA Zentroa,AZKUNA Zentroa está ubicado en pleno centro de...,Auditorios; Museos; Galerías de arte y salas d...,Bilbao,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/azkuna-...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
85,Cristóbal Balenciaga Museoa,El Cristóbal Balenciaga Museoa está dedicado a...,Auditorios; Museos; Galerías de arte y salas d...,Getaria,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/top10/museos/c...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
88,Centro de Interpretación del Camino de Santiago,CERRADO TEMPORALMENTEEl Centro de Interpretaci...,Auditorios; Museos; Galerías de arte y salas d...,Orio,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/centro-...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
91,Izenaduba Basoa,A través de las visitas teatralizadas que se o...,Auditorios; Museos; Galerías de arte y salas d...,Mungia,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/izenadu...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
94,Centro de Interpretación de la Vía Verde del F...,El Centro de Interpretación de la Vía Verde de...,Auditorios; Museos; Galerías de arte y salas d...,Antoñana,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/centro-...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
97,Centro de Atención e Interpretación del Valle ...,La visita al Valle Salado de Añana comienza en...,Auditorios; Museos; Galerías de arte y salas d...,Salinas de Añana/Gesaltza Añana,NaN,NaN,NaN,NaN,NaN,NaN,...,1,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/centro-...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
102,Centro de Interpretación de Arma Plaza,El Centro de Interpretación sito en la Arma Pl...,Auditorios; Museos; Galerías de arte y salas d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/centro-...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
103,Centro de Interpretación de Debagoiena,Desde allí se organizan multitud de actividade...,Auditorios; Museos; Galerías de arte y salas d...,Oñati,NaN,NaN,NaN,NaN,NaN,NaN,...,20,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/centro-...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...
118,Museo Aguinaga de Mercedes-Benz,El Museo Aguinaga de Barakaldo es el escenario...,Auditorios; Museos; Galerías de arte y salas d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48,España,108,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/museos/museo-a...,https://turismoa.euskadi.eus/webtur00-content/...,https://turismoa.euskadi.eus/contenidos/h_cult...,https://turismoa.euskadi.eus/contenidos/h_cult...

# PATRIMONIO CULTURAL

In [51]:
# https://www.geo.euskadi.eus/patrimonio-cultural/webgeo00-dataset/es/

# MUSEOS + PATRIMONIO

In [102]:
df = pd.read_excel("Museos_patrimonio_limpio.xlsx")
df

,Nombre,Descripción,Tipo de Plantilla,Dirección,Municipio,Provincia,Postal Code,Marcas,Email,Teléfono,WEB,URL amigable,Visita Guiada,Capacidad,Tienda,Tipo de Cultura,Coordenadas GPS,LATWGS84,LONWGS84
0,Museo Bibat,Ubicado en el Casco Antiguo de Vitoria-Gasteiz...,Auditorios; Museos; Galerías de arte y salas d...,"Cuchillería, 54. Junto al Palacio de Bendaña.",Vitoria-Gasteiz,Araba/Álava,1001.0,Vitoria-Gasteiz,bibat@araba.eus,945 203 700,https://fourniermuseoabibat.eus/es/inicio,https://turismoa.euskadi.eus/es/museos/museo-b...,1.0,0.0,1.0,Otros,"42.8493094,-2.6711764000000358",42.849309,-2.671176
1,Museo de Faroles de la Cofradía de la Virgen B...,Este original museo alberga las 267 piezas de ...,Auditorios; Museos; Galerías de arte y salas d...,"Zapatería, 33",Vitoria-Gasteiz,Araba/Álava,1001.0,Vitoria-Gasteiz,info@cofradiavirgenblanca.com,945 277 077,http://www.cofradiavirgenblanca.com/,https://turismoa.euskadi.eus/es/museos/museo-d...,1.0,100.0,NaN,Otros,"42.84809749,-2.67413986",42.848097,-2.674140
2,Museo de Ciencias Naturales de Álava,El Museo de Ciencias Naturales de Álava cuenta...,Auditorios; Museos; Galerías de arte y salas d...,"Fundadora de las Siervas de Jesús, 24",Vitoria-Gasteiz,Araba/Álava,1001.0,Vitoria-Gasteiz,mcna@araba.eus,945 181 924,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,1.0,100.0,NaN,Ciencias Naturales,"42.8502903,-2.67462519",42.850290,-2.674625
3,Artium museoa,El/la visitante podrá encontrar en exposición ...,Auditorios; Museos; Galerías de arte y salas d...,"Francia, 24",Vitoria-Gasteiz,Araba/Álava,1002.0,Vitoria-Gasteiz,museo@artium.eus,945 209 020,https://www.artium.eus/es/,https://turismoa.euskadi.eus/es/museos/artium-...,1.0,2892.0,1.0,Arte,"42.84942634,-2.66802071",42.849426,-2.668021
4,Museo de Armería,El Museo de Armería ofrece al visitante una ex...,Auditorios; Museos; Galerías de arte y salas d...,"Paseo de Fray Francisco de Vitoria, 3",Vitoria-Gasteiz,Araba/Álava,1001.0,Vitoria-Gasteiz,museoarmeria@araba.eus,945 181 925,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,1.0,92.0,NaN,Otros,"42.8413475,-2.678544200000033",42.841347,-2.678544
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1244,Cargadero de Mollarri,El cargadero de minerales Malla Harria o Molla...,Patrimonio cultural,Talaimendi,Zarautz,Gipuzkoa,20800.0,Costa Vasca,turismoa@zarautz.eus,943 830 990,https://www.turismozarautz.eus/es/-/malla-arri...,https://turismoa.euskadi.eus/es/patrimonio-cul...,NaN,NaN,NaN,NaN,"43.29325589367154,-2.1484063708862244",43.293256,-2.148406
1245,Jardín Botánico Ramón Rubial,"El Jardín Botánico Ramón Rubial, en el corazón...",Patrimonio cultural,"La Torre, 30",Barakaldo,Bizkaia,48902.0,Costa Vasca,naturgela@barakaldo.eus,944 375 805,http://naturgelabarakaldo.blogspot.com/,https://turismoa.euskadi.eus/es/patrimonio-cul...,NaN,NaN,NaN,NaN,"43.2924701463708,-3.001095232818607",43.292470,-3.001095
1246,Vivienda Minera de La Arboleda,"A mediados de 1870, la explotación minera de l...",Patrimonio cultural,La Arboleda,Valle de Trápaga-Trapagaran,Bizkaia,48510.0,Montes y Valles vascos,informacion@meatzaldea.eus,946 363 682,http://www.meatzaldea.eus/,https://turismoa.euskadi.eus/es/patrimonio-cul...,NaN,NaN,NaN,NaN,"43.284173856791064,-3.0536127190143625",43.284174,-3.053613
1247,Jardín Botánico Berrizjauregi,El Jardín Botánico Berrizjauregi está ubicado ...,Patrimonio cultural,"Iturritza Kalea, 51",Berriz,Bizkaia,48240.0,Montes y Valles vascos,NaN,946 824 036,NaN,https://turismoa.euskadi.eus/es/patrimonio-cul...,NaN,NaN,NaN,NaN,"43.1748466,-2.5775427",43.174847,-2.577543
1248,Castillo de Portilla,"Está ubicado en Portilla, concejo del municipi...",Patrimonio cultural,NaN,Zambrana,Araba/Álava,NaN,Montes y Valles vascos,NaN,NaN,https://turismo.euskadi.eus/es/patrimonio-cult...,https://turismoa.euskadi.eus/es/patrimonio-cul...,NaN,NaN,NaN,NaN,"42.6703698,-2.8336449",42.670370,-2.833645

In [103]:
df = df.drop_duplicates(subset=['Nombre'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 643 entries, 0 to 1200
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Nombre             643 non-null    object
 1   Descripción        643 non-null    object
 2   Tipo de Plantilla  643 non-null    object
 3   Dirección          606 non-null    object
 4   Municipio          642 non-null    object
 5   Provincia          643 non-null    object
 6   Postal Code        592 non-null    float64
 7   Marcas             642 non-null    object
 8   Email              518 non-null    object
 9   Teléfono           612 non-null    object
 10  WEB                247 non-null    object
 11  URL amigable       643 non-null    object
 12  Visita Guiada      254 non-null    float64
 13  Capacidad          174 non-null    float64
 14  Tienda             87 non-null     float64
 15  Tipo de Cultura    122 non-null    object
 16  Coordenadas GPS    636 non-null    object
 17  LATWGS84           636 non-null    float64
 18  LONWGS84           636 non-null    float64
dtypes: float64(6), object(13)
memory usage: 100.5+ KB

In [104]:
df.rename(columns={'Tipo de Plantilla': 'Tipo de lugar'}, inplace=True)
df.loc[:150, 'Tipo de lugar'] = 'Museo'

C:\Users\cchia\AppData\Local\Temp\ipykernel_15832\651981180.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'Tipo de Plantilla': 'Tipo de lugar'}, inplace=True)

In [105]:
df[df.isna().any(axis=1)]

,Nombre,Descripción,Tipo de lugar,Dirección,Municipio,Provincia,Postal Code,Marcas,Email,Teléfono,WEB,URL amigable,Visita Guiada,Capacidad,Tienda,Tipo de Cultura,Coordenadas GPS,LATWGS84,LONWGS84
1,Museo de Faroles de la Cofradía de la Virgen B...,Este original museo alberga las 267 piezas de ...,Museo,"Zapatería, 33",Vitoria-Gasteiz,Araba/Álava,1001.0,Vitoria-Gasteiz,info@cofradiavirgenblanca.com,945 277 077,http://www.cofradiavirgenblanca.com/,https://turismoa.euskadi.eus/es/museos/museo-d...,1.0,100.0,NaN,Otros,"42.84809749,-2.67413986",42.848097,-2.674140
2,Museo de Ciencias Naturales de Álava,El Museo de Ciencias Naturales de Álava cuenta...,Museo,"Fundadora de las Siervas de Jesús, 24",Vitoria-Gasteiz,Araba/Álava,1001.0,Vitoria-Gasteiz,mcna@araba.eus,945 181 924,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,1.0,100.0,NaN,Ciencias Naturales,"42.8502903,-2.67462519",42.850290,-2.674625
4,Museo de Armería,El Museo de Armería ofrece al visitante una ex...,Museo,"Paseo de Fray Francisco de Vitoria, 3",Vitoria-Gasteiz,Araba/Álava,1001.0,Vitoria-Gasteiz,museoarmeria@araba.eus,945 181 925,NaN,https://turismoa.euskadi.eus/es/museos/museo-d...,1.0,92.0,NaN,Otros,"42.8413475,-2.678544200000033",42.841347,-2.678544
5,Conjunto Monumental de Iruña-Veleia,El yacimiento arqueológico de Iruña-Veleia aba...,Museo,Trespuentes y Víllodas,Iruña Oka/Iruña de Oca,Araba/Álava,NaN,Montes y Valles vascos,NaN,618 539 353,https://www.irunadeoca.com/ayuntamiento-iruna-...,https://turismoa.euskadi.eus/es/museos/conjunt...,1.0,0.0,NaN,Historia,NaN,NaN,NaN
7,Villa Lucía. Centro Temático del vino,Situado en una antigua finca de recreo del fab...,Museo,Ctra. Logroño s/n,Laguardia,Araba/Álava,1300.0,Rioja Alavesa,reservas@villa-lucia.com,945 600 032,https://villa-lucia.com/,https://turismoa.euskadi.eus/es/museos/villa-l...,NaN,0.0,NaN,Gastronomía,"42.54833710996413,-2.5782178043932618",42.548337,-2.578218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789,Estudio Iñigo Manterola,"Iñigo Manterola es un artista polifacético, cu...",Auditorios; Museos; Galerías de arte y salas d...,"Polígono Errotaberri, Ola Bidea s/n",Zarautz,Gipuzkoa,20800.0,Costa Vasca,NaN,617 332 813,https://www.inigomanterola.com/,https://turismoa.euskadi.eus/es/museos/estudio...,NaN,0.0,NaN,NaN,"43.27426,-2.1686642",43.274260,-2.168664
791,Castillo de Portilla,"Está ubicado en Portilla, concejo del municipi...",Patrimonio cultural,NaN,Zambrana,Araba/Álava,NaN,Montes y Valles vascos,NaN,NaN,https://turismo.euskadi.eus/es/patrimonio-cult...,https://turismoa.euskadi.eus/es/patrimonio-cul...,NaN,NaN,NaN,NaN,"42.6703698,-2.8336449",42.670370,-2.833645
792,ABAO Bilbao Ópera,ABAO Bilbao Ópera es una institución cultural ...,Auditorios; Museos; Galerías de arte y salas d...,"José María Olavarri, 2",Bilbao,Bizkaia,NaN,Bilbao,abao@abao.org,NaN,https://www.abao.org/es,https://turismoa.euskadi.eus/es/museos/abao-bi...,NaN,0.0,NaN,NaN,"43.2603473,-2.9274007",43.260347,-2.927401
793,Euskadiko Orkestra,Nace en una sociedad en la que la música es un...,Auditorios; Museos; Galerías de arte y salas d...,"Miramon pasealekua, 124",Donostia / San Sebastián,Gipuzkoa,NaN,San Sebastián,NaN,943 013 232,https://www.euskadikoorkestra.eus/,https://turismoa.euskadi.eus/es/museos/euskadi...,NaN,0.0,NaN,NaN,"43.2951782,-1.9773335",43.295178,-1.977334
1200,Conjunto Histórico Artístico El Camino de Sant...,"El Camino de Santiago, por el que transitaran ...",Patrimonio cultural,<em>El recorrido comienza en Hondarribia y fin...,NaN,Gipuzkoa;Bizkaia,NaN,NaN,NaN,NaN,NaN,https://turismoa.euskadi.eus/es/patrimonio-cul...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [106]:
df[['Tienda', 'Visita Guiada', 'Capacidad']] = df[['Tienda', 'Visita Guiada', 'Capacidad']].fillna(0)

C:\Users\cchia\AppData\Local\Temp\ipykernel_15832\1753269310.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Tienda', 'Visita Guiada', 'Capacidad']] = df[['Tienda', 'Visita Guiada', 'Capacidad']].fillna(0)

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 643 entries, 0 to 1200
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Nombre           643 non-null    object
 1   Descripción      643 non-null    object
 2   Tipo de lugar    643 non-null    object
 3   Dirección        606 non-null    object
 4   Municipio        642 non-null    object
 5   Provincia        643 non-null    object
 6   Postal Code      592 non-null    float64
 7   Marcas           642 non-null    object
 8   Email            518 non-null    object
 9   Teléfono         612 non-null    object
 10  WEB              247 non-null    object
 11  URL amigable     643 non-null    object
 12  Visita Guiada    643 non-null    float64
 13  Capacidad        643 non-null    float64
 14  Tienda           643 non-null    float64
 15  Tipo de Cultura  122 non-null    object
 16  Coordenadas GPS  636 non-null    object
 17  LATWGS84         636 non-null    float64
 18  LONWGS84         636 non-null    float64
dtypes: float64(6), object(13)
memory usage: 116.6+ KB

In [108]:
df[df["Marcas"].isna()]
df = df.dropna(subset=['Marcas', 'Coordenadas GPS', 'LATWGS84', 'LONWGS84'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 636 entries, 0 to 793
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Nombre           636 non-null    object
 1   Descripción      636 non-null    object
 2   Tipo de lugar    636 non-null    object
 3   Dirección        602 non-null    object
 4   Municipio        636 non-null    object
 5   Provincia        636 non-null    object
 6   Postal Code      591 non-null    float64
 7   Marcas           636 non-null    object
 8   Email            514 non-null    object
 9   Teléfono         607 non-null    object
 10  WEB              244 non-null    object
 11  URL amigable     636 non-null    object
 12  Visita Guiada    636 non-null    float64
 13  Capacidad        636 non-null    float64
 14  Tienda           636 non-null    float64
 15  Tipo de Cultura  121 non-null    object
 16  Coordenadas GPS  636 non-null    object
 17  LATWGS84         636 non-null    float64
 18  LONWGS84         636 non-null    float64
dtypes: float64(6), object(13)
memory usage: 99.4+ KB

# MUSEOS Y PATRIMONIO ENRIQUECIDO

In [2]:
df_def = pd.read_csv("museos_patrimonio_enriquecido.csv")
df_def

,Nombre,Descripción,Tipo de lugar,Dirección,Municipio,Provincia,Postal Code,Marcas,Email,Teléfono,...,Visita Guiada,Capacidad,Tienda,Tipo de Cultura,Coordenadas GPS,LATWGS84,LONWGS84,valoracion,num_resenas,url_imagen
0,Museo Bibat,Ubicado en el Casco Antiguo de Vitoria-Gasteiz...,Museo,"Cuchillería, 54. Junto al Palacio de Bendaña.",Vitoria-Gasteiz,Araba/Álava,1001.0,Vitoria-Gasteiz,bibat@araba.eus,945 203 700,...,1.0,0.0,1.0,Otros,"42.8493094,-2.6711764000000358",42.849309,-2.671176,4.4,242.0,https://places.googleapis.com/v1/places/ChIJd6...
1,Museo de Faroles de la Cofradía de la Virgen B...,Este original museo alberga las 267 piezas de ...,Museo,"Zapatería, 33",Vitoria-Gasteiz,Araba/Álava,1001.0,Vitoria-Gasteiz,info@cofradiavirgenblanca.com,945 277 077,...,1.0,100.0,0.0,Otros,"42.84809749,-2.67413986",42.848097,-2.674140,4.7,250.0,https://places.googleapis.com/v1/places/ChIJN4...
2,Museo de Ciencias Naturales de Álava,El Museo de Ciencias Naturales de Álava cuenta...,Museo,"Fundadora de las Siervas de Jesús, 24",Vitoria-Gasteiz,Araba/Álava,1001.0,Vitoria-Gasteiz,mcna@araba.eus,945 181 924,...,1.0,100.0,0.0,Ciencias Naturales,"42.8502903,-2.67462519",42.850290,-2.674625,4.6,770.0,https://places.googleapis.com/v1/places/ChIJHQ...
3,Artium museoa,El/la visitante podrá encontrar en exposición ...,Museo,"Francia, 24",Vitoria-Gasteiz,Araba/Álava,1002.0,Vitoria-Gasteiz,museo@artium.eus,945 209 020,...,1.0,2892.0,1.0,Arte,"42.84942634,-2.66802071",42.849426,-2.668021,4.1,2644.0,https://places.googleapis.com/v1/places/ChIJfz...
4,Museo de Armería,El Museo de Armería ofrece al visitante una ex...,Museo,"Paseo de Fray Francisco de Vitoria, 3",Vitoria-Gasteiz,Araba/Álava,1001.0,Vitoria-Gasteiz,museoarmeria@araba.eus,945 181 925,...,1.0,92.0,0.0,Otros,"42.8413475,-2.678544200000033",42.841347,-2.678544,4.7,729.0,https://places.googleapis.com/v1/places/ChIJ2W...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,Galería J. M. Lumbreras,Esta galería posee tres salas de exposición y ...,Auditorios; Museos; Galerías de arte y salas d...,c/ Henao 3,Bilbao,Bizkaia,48009.0,Bilbao,galeria@galerialumbreras.com,944 244 545,...,0.0,0.0,0.0,Patrimonio Cultural,"43.26396,-2.9294957",43.263960,-2.929496,4.7,76.0,https://places.googleapis.com/v1/places/ChIJyS...
632,Estudio Iñigo Manterola,"Iñigo Manterola es un artista polifacético, cu...",Auditorios; Museos; Galerías de arte y salas d...,"Polígono Errotaberri, Ola Bidea s/n",Zarautz,Gipuzkoa,20800.0,Costa Vasca,NaN,617 332 813,...,0.0,0.0,0.0,Patrimonio Cultural,"43.27426,-2.1686642",43.274260,-2.168664,4.9,37.0,https://places.googleapis.com/v1/places/ChIJG0...
633,Castillo de Portilla,"Está ubicado en Portilla, concejo del municipi...",Patrimonio cultural,NaN,Zambrana,Araba/Álava,NaN,Montes y Valles vascos,NaN,NaN,...,0.0,0.0,0.0,Patrimonio Cultural,"42.6703698,-2.8336449",42.670370,-2.833645,NaN,NaN,NaN
634,ABAO Bilbao Ópera,ABAO Bilbao Ópera es una institución cultural ...,Auditorios; Museos; Galerías de arte y salas d...,"José María Olavarri, 2",Bilbao,Bizkaia,NaN,Bilbao,abao@abao.org,NaN,...,0.0,0.0,0.0,Patrimonio Cultural,"43.2603473,-2.9274007",43.260347,-2.927401,4.4,78.0,https://places.googleapis.com/v1/places/ChIJu-...
635,Euskadiko Orkestra,Nace en una sociedad en la que la música es un...,Auditorios; Museos; Galerías de arte y salas d...,"Miramon pasealekua, 124",Donostia / San Sebastián,Gipuzkoa,NaN,San Sebastián,NaN,943 013 232,...,0.0,0.0,0.0,Patrimonio Cultural,"43.2951782,-1.9773335",43.295178,-1.977334,4.6,199.0,https://places.googleapis.com/v1/places/ChIJrx...

In [6]:
df_def.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Nombre           636 non-null    object
 1   Descripción      636 non-null    object
 2   Tipo de lugar    636 non-null    object
 3   Dirección        602 non-null    object
 4   Municipio        636 non-null    object
 5   Provincia        636 non-null    object
 6   Postal Code      591 non-null    float64
 7   Marcas           636 non-null    object
 8   Email            514 non-null    object
 9   Teléfono         607 non-null    object
 10  WEB              244 non-null    object
 11  URL amigable     636 non-null    object
 12  Visita Guiada    636 non-null    float64
 13  Capacidad        636 non-null    float64
 14  Tienda           636 non-null    float64
 15  Tipo de Cultura  602 non-null    object
 16  Coordenadas GPS  636 non-null    object
 17  LATWGS84         636 non-null    float64
 18  LONWGS84         636 non-null    float64
 19  valoracion       562 non-null    float64
 20  num_resenas      562 non-null    float64
 21  url_imagen       590 non-null    object
dtypes: float64(8), object(14)
memory usage: 109.4+ KB

In [5]:
df_def[df_def["valoracion"] < 4.2]

,Nombre,Descripción,Tipo de lugar,Dirección,Municipio,Provincia,Postal Code,Marcas,Email,Teléfono,...,Visita Guiada,Capacidad,Tienda,Tipo de Cultura,Coordenadas GPS,LATWGS84,LONWGS84,valoracion,num_resenas,url_imagen
3,Artium museoa,El/la visitante podrá encontrar en exposición ...,Museo,"Francia, 24",Vitoria-Gasteiz,Araba/Álava,1002.0,Vitoria-Gasteiz,museo@artium.eus,945 209 020,...,1.0,2892.0,1.0,Arte,"42.84942634,-2.66802071",42.849426,-2.668021,4.1,2644.0,https://places.googleapis.com/v1/places/ChIJfz...
34,Z ESPACIO CULTURAL,Espacio Cultural creado por Ignacio Zuloaga en...,Museo,"Bº Santiago auzoa, 3",Zumaia,Gipuzkoa,20750.0,Costa Vasca,info@espaciozuloaga.com,34 677 078 445,...,1.0,50.0,0.0,Arte,"43.2979527,-2.2477350000000342",43.297953,-2.247735,3.8,43.0,https://places.googleapis.com/v1/places/ChIJ1y...
44,Museo Taurino de Bilbao,El Museo Taurino repasa la historia de la taur...,Museo,"Plaza de Toros de Vista Alegre. Martín Agüero, 1",Bilbao,Bizkaia,48012.0,Bilbao,info@plazatorosbilbao.com,944 448 698,...,1.0,80.0,1.0,Otros,"43.2555485729847,-2.9375311059832687",43.255549,-2.937531,3.2,102.0,https://places.googleapis.com/v1/places/ChIJc2...
57,Parque Cultural de Zerain,El Museo Etnográfico alberga más de 200 elemen...,Museo,"Herriko Plaza, s/n",Zerain,Gipuzkoa,20214.0,Montes y Valles vascos,turismobulegoa@zerain.eus,943 801 505,...,1.0,40.0,1.0,Etnografía,"43.01280932708332,-2.273073426458716",43.012809,-2.273073,4.1,10.0,https://places.googleapis.com/v1/places/ChIJqW...
63,Servicio de Patrimonio Histórico-Artístico y A...,Se debe llamar a este servicio para concertar ...,Museo,"Plaza de la Provincia 5, 3ª planta",Vitoria-Gasteiz,Araba/Álava,1007.0,Vitoria-Gasteiz,afa-dfa@araba.eus,945 181 818,...,0.0,0.0,0.0,Otros,"42.84157305,-2.67964698",42.841573,-2.679647,3.8,66.0,https://places.googleapis.com/v1/places/ChIJbV...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,Senda del Lea y Marierrota,En la comarca de Lea-Artibai se encuentra la S...,Patrimonio cultural,NaN,Lekeitio,Bizkaia,NaN,Costa Vasca,NaN,946 844 017,...,0.0,0.0,0.0,Patrimonio Cultural,"43.35951898654631,-2.497720495861804",43.359519,-2.497720,4.0,9.0,https://places.googleapis.com/v1/places/ChIJa3...
610,Bosque Industrial de Ajuria & Urigoitia,El entorno de la fundición Ajuria y Urigoitia ...,Patrimonio cultural,NaN,Asparrena,Araba/Álava,NaN,Montes y Valles vascos,NaN,NaN,...,0.0,0.0,0.0,Patrimonio Cultural,"42.8892222,-2.3123031000000083",42.889222,-2.312303,4.1,86.0,https://places.googleapis.com/v1/places/ChIJbc...
612,Marierrota,Marierrota es un molino de mareas situado al f...,Patrimonio cultural,Barrio Likoa,Mendexa,Bizkaia,48289.0,Costa Vasca,turismo@lekeitio.eus,946 844 017,...,0.0,0.0,0.0,Patrimonio Cultural,"43.35983100601811,-2.49829985300903",43.359831,-2.498300,4.0,9.0,https://places.googleapis.com/v1/places/ChIJa3...
613,Molino de Fandería ? Casa del río,El Molino de Fandería atestigua la pujanza y e...,Patrimonio cultural,"Dolores Ibarruri Zumardia, z/g",Errenteria,Gipuzkoa,NaN,Montes y Valles vascos,turismoa@oarsoaldea.eus,943 494 521,...,0.0,0.0,0.0,Patrimonio Cultural,"43.308972,-1.888",43.308972,-1.888000,4.0,193.0,https://places.googleapis.com/v1/places/ChIJsx...
621,Quinta Torre,Quinta Torre es un espectacular edificio situa...,Patrimonio cultural,Errementeria. 29,Bakio,Bizkaia,NaN,Costa Vasca,turismo@bakio.eus,946 193 395,...,0.0,0.0,0.0,Patrimonio Cultural,"43.421046722687066,-2.8156855529174907",43.421047,-2.815686,4.1,10.0,https://places.googleapis.com/v1/places/ChIJ8f...