# KAGGLE 1: MACHINE LEARNING ORDENADORES

### LIMPIEZA DE DATOS

In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"train.csv")

In [3]:
df.head()

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,697,705,Asus,Chromebook Flip,2 in 1 Convertible,12.5,Full HD / Touchscreen 1920x1080,Intel Core M M3-6Y30 0.9GHz,4GB,64GB Flash Storage,Intel HD Graphics 515,Chrome OS,1.2kg,669.0
1,435,442,Asus,Rog Strix,Gaming,17.3,Full HD 1920x1080,AMD Ryzen 1600 3.2GHz,8GB,256GB SSD + 1TB HDD,AMD Radeon RX 580,Windows 10,3.2kg,1695.0
2,735,743,Lenovo,V310-15IKB (i7-7500U/4GB/1TB/FHD/W10),Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,4GB,1TB HDD,Intel HD Graphics 620,Windows 10,1.85kg,779.0
3,864,875,Dell,XPS 13,Ultrabook,13.3,Quad HD+ / Touchscreen 3200x1800,Intel Core i7 7660U 2.5GHz,16GB,512GB SSD,Intel Iris Plus Graphics 640,Windows 10,1.29kg,2240.0
4,1176,1194,Lenovo,B51-80 (i7-6500U/4GB/1008GB/FHD/W7),Notebook,15.6,Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,1.0TB Hybrid,Intel HD Graphics 520,Windows 7,2.32kg,825.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                912 non-null    int64
 1   laptop_ID         912 non-null    int64
 2   Company           912 non-null    str
 3   Product           912 non-null    str
 4   TypeName          912 non-null    str
 5   Inches            912 non-null    float64
 6   ScreenResolution  912 non-null    str
 7   Cpu               912 non-null    str
 8   Ram               912 non-null    str
 9   Memory            912 non-null    str
 10  Gpu               912 non-null    str
 11  OpSys             912 non-null    str
 12  Weight            912 non-null    str
 13  Price_euros       912 non-null    float64
dtypes: float64(2), int64(2), str(10)
memory usage: 99.9 KB

### LIMPIEZA DE DATOS

Dropear laptop_ID:

In [5]:
df.drop(["laptop_ID"], axis=1, inplace=True)

Limpio Ram y Weight para quitar GB y kg, pasándolas a int y float respectivamente

In [6]:
df['Ram'] = df['Ram'].str.replace('GB', '').astype(int)

df['Weight'] = df['Weight'].str.replace('kg', '').astype(float)

Paso company a números con LabelEncoder

In [7]:
df["Company"].unique()

<StringArray>
[     'Asus',    'Lenovo',      'Dell',  'Mediacom',   'Toshiba',        'HP',
      'Acer',     'Apple',       'MSI',   'Fujitsu',   'Samsung',     'Chuwi',
 'Microsoft',     'Razer',    'Xiaomi',    'Huawei',    'Google',      'Vero',
        'LG']
Length: 19, dtype: str

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Company'] = le.fit_transform(df['Company'])

In [9]:
dict(zip(le.classes_, le.transform(le.classes_)))

{'Acer': np.int64(0),
 'Apple': np.int64(1),
 'Asus': np.int64(2),
 'Chuwi': np.int64(3),
 'Dell': np.int64(4),
 'Fujitsu': np.int64(5),
 'Google': np.int64(6),
 'HP': np.int64(7),
 'Huawei': np.int64(8),
 'LG': np.int64(9),
 'Lenovo': np.int64(10),
 'MSI': np.int64(11),
 'Mediacom': np.int64(12),
 'Microsoft': np.int64(13),
 'Razer': np.int64(14),
 'Samsung': np.int64(15),
 'Toshiba': np.int64(16),
 'Vero': np.int64(17),
 'Xiaomi': np.int64(18)}

In [10]:
df.head()

,id,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,697,2,Chromebook Flip,2 in 1 Convertible,12.5,Full HD / Touchscreen 1920x1080,Intel Core M M3-6Y30 0.9GHz,4,64GB Flash Storage,Intel HD Graphics 515,Chrome OS,1.20,669.0
1,435,2,Rog Strix,Gaming,17.3,Full HD 1920x1080,AMD Ryzen 1600 3.2GHz,8,256GB SSD + 1TB HDD,AMD Radeon RX 580,Windows 10,3.20,1695.0
2,735,10,V310-15IKB (i7-7500U/4GB/1TB/FHD/W10),Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,4,1TB HDD,Intel HD Graphics 620,Windows 10,1.85,779.0
3,864,4,XPS 13,Ultrabook,13.3,Quad HD+ / Touchscreen 3200x1800,Intel Core i7 7660U 2.5GHz,16,512GB SSD,Intel Iris Plus Graphics 640,Windows 10,1.29,2240.0
4,1176,10,B51-80 (i7-6500U/4GB/1008GB/FHD/W7),Notebook,15.6,Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,4,1.0TB Hybrid,Intel HD Graphics 520,Windows 7,2.32,825.0

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                912 non-null    int64
 1   Company           912 non-null    int64
 2   Product           912 non-null    str
 3   TypeName          912 non-null    str
 4   Inches            912 non-null    float64
 5   ScreenResolution  912 non-null    str
 6   Cpu               912 non-null    str
 7   Ram               912 non-null    int64
 8   Memory            912 non-null    str
 9   Gpu               912 non-null    str
 10  OpSys             912 non-null    str
 11  Weight            912 non-null    float64
 12  Price_euros       912 non-null    float64
dtypes: float64(3), int64(3), str(7)
memory usage: 92.8 KB

In [12]:
df["OpSys"].unique()

<StringArray>
[   'Chrome OS',   'Windows 10',    'Windows 7',        'Linux',
        'No OS',        'macOS',     'Mac OS X', 'Windows 10 S',
      'Android']
Length: 9, dtype: str

In [13]:
df['OpSys'].value_counts()

OpSys
Windows 10      745
Linux            46
No OS            46
Windows 7        33
Chrome OS        18
macOS            11
Mac OS X          6
Windows 10 S      5
Android           2
Name: count, dtype: int64

In [14]:
# junto todos los windows, junto todos los mac y elimino android (son solo 2 datos)
df = df[df["OpSys"] != "Android"]

df["OpSys"] = df["OpSys"].replace({
    'Mac OS X': 'macOS',
    'Windows 10 S': 'Windows',
    'Windows 10': 'Windows',
    'Windows 7': 'Windows',
})

df["OpSys"] = le.fit_transform(df["OpSys"])

In [15]:
dict(zip(le.classes_, le.transform(le.classes_)))

{'Chrome OS': np.int64(0),
 'Linux': np.int64(1),
 'No OS': np.int64(2),
 'Windows': np.int64(3),
 'macOS': np.int64(4)}

TypeName tiene solo 6 entradas, así que las paso con labelencoder:

In [16]:
df["TypeName"].value_counts()

TypeName
Notebook              516
Gaming                143
Ultrabook             130
2 in 1 Convertible     82
Workstation            22
Netbook                17
Name: count, dtype: int64

In [17]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['TypeName'] = le.fit_transform(df['TypeName'])

In [18]:
dict(zip(le.classes_, le.transform(le.classes_)))

{'2 in 1 Convertible': np.int64(0),
 'Gaming': np.int64(1),
 'Netbook': np.int64(2),
 'Notebook': np.int64(3),
 'Ultrabook': np.int64(4),
 'Workstation': np.int64(5)}

Elimino la columna "product" porque contiene información que tienen otras columnas y tampoco me parece relevant el nombre del producto para el precio, sino sus características

In [19]:
df.drop(["Product"], axis=1, inplace=True)

Voy a ver qué hacer con las últimas 4:

In [20]:
df["ScreenResolution"].unique()

<StringArray>
[              'Full HD / Touchscreen 1920x1080',
                             'Full HD 1920x1080',
              'Quad HD+ / Touchscreen 3200x1800',
                   'IPS Panel Full HD 1920x1080',
                   'IPS Panel Full HD 2560x1440',
                           'IPS Panel 2560x1440',
                                      '1366x768',
     'IPS Panel Full HD / Touchscreen 1920x1080',
                            'IPS Panel 1366x768',
                  'IPS Panel Quad HD+ 2560x1440',
                                      '1440x900',
    'IPS Panel Quad HD+ / Touchscreen 3200x1800',
            'IPS Panel Retina Display 2560x1600',
                                     '2560x1440',
            'IPS Panel Retina Display 2304x1440',
                          'Touchscreen 1366x768',
 'IPS Panel 4K Ultra HD / Touchscreen 3840x2160',
                         '4K Ultra HD 3840x2160',
            'IPS Panel Retina Display 2736x1824',
               'IPS Panel Touchscreen 2560x1440',
                                      '1600x900',
               'IPS Panel 4K Ultra HD 3840x2160',
           '4K Ultra HD / Touchscreen 3840x2160',
                'IPS Panel Touchscreen 1366x768',
                         'Touchscreen 2256x1504',
                            'Quad HD+ 3200x1800',
 'IPS Panel Touchscreen / 4K Ultra HD 3840x2160',
                                     '1920x1080',
            'IPS Panel Retina Display 2880x1800',
                   'IPS Panel Full HD 2160x1440',
               'IPS Panel Touchscreen 1920x1200',
                         'Touchscreen 2400x1600',
                         'Touchscreen 2560x1440',
                  'IPS Panel Quad HD+ 3200x1800',
              'Touchscreen / Quad HD+ 3200x1800',
                   'IPS Panel Full HD 1920x1200',
               'Touchscreen / Full HD 1920x1080']
Length: 37, dtype: str

In [21]:
# Touchscreen: 1 si tiene, 0 si no (que la pantalla sea táctil)
df['Touchscreen'] = df['ScreenResolution'].str.contains('Touchscreen').astype(int)

# IPS Panel: 1 si tiene, 0 si no (IPS más caro, temas de color y ángulos de la pantalla)
df['IPS'] = df['ScreenResolution'].str.contains('IPS').astype(int)

# Resolución: extraer solo los píxeles
df['Resolution'] = df['ScreenResolution'].str.extract(r'(\d+x\d+)')

In [22]:
# calcular píxeles totales (anchoXalto); así el modelo entiendo que a más píxeles, más caro
df['Total_pixels'] = df['Resolution'].apply(lambda x: int(x.split('x')[0]) * int(x.split('x')[1]))

df.drop(['ScreenResolution', 'Resolution'], axis=1, inplace=True)

In [23]:
df["Cpu"].unique()

<StringArray>
[         'Intel Core M M3-6Y30 0.9GHz',
                'AMD Ryzen 1600 3.2GHz',
           'Intel Core i7 7500U 2.7GHz',
           'Intel Core i7 7660U 2.5GHz',
           'Intel Core i7 6500U 2.5GHz',
 'Intel Celeron Quad Core N3450 1.1GHz',
 'Intel Pentium Quad Core N4200 1.1GHz',
          'Intel Core i7 7700HQ 2.8GHz',
          'Intel Core i7 7820HK 2.9GHz',
           'Intel Core i5 6300U 2.4GHz',
 ...
          'Intel Core i7 6500U 2.50GHz',
 'Intel Pentium Quad Core N3700 1.6GHz',
                 'Intel Core i7 2.8GHz',
           'Intel Core i7 7500U 2.5GHz',
                 'Intel Core i7 2.9GHz',
            'AMD A6-Series 9220 2.9GHz',
          'Intel Core i7 7700HQ 2.7GHz',
                 'Intel Core i5 1.3GHz',
          'AMD A10-Series 9600P 2.4GHz',
              'AMD A6-Series 7310 2GHz']
Length: 102, dtype: str

In [24]:
# Velocidad en GHz
df['CPU_GHz'] = df['Cpu'].str.extract(r'(\d+\.?\d*)GHz').astype(float)

# Marca: Intel (1) o AMD (0) 
df['CPU_brand'] = df['Cpu'].apply(lambda x: x.split()[0]) # coge si es AMD o Intel (primera palabra)
df['CPU_brand'] = le.fit_transform(df['CPU_brand']) # aquí aplica 0 a AMD y 1 a Intel

In [25]:
# diccionario de número ascendente por categoría de procesador
cpu_order = {
    # Intel gama baja
    'Atom': 0, 'Celeron': 1, 'Pentium': 2,
    # AMD gama baja
    'E-Series': 3, 'A4-Series': 4, 'A6-Series': 5, 'A8-Series': 6,
    'A9-Series': 7, 'A10-Series': 8, 'A12-Series': 9,
    # Intel gama media-alta
    'Core M': 10, 'Core i3': 11, 'Core i5': 12, 'Core i7': 13,
    # Gama profesional/alta
    'Xeon': 14, 'Ryzen': 15
    }

# establecer los números a cada categoría

def extract_cpu_model(cpu):
    parts = cpu.split()
    # Intel Core i5/i7/i3/M necesita 2 palabras
    if parts[1] == 'Core':
        return parts[1] + ' ' + parts[2]
    # resto con 1 palabra
    return parts[1]

df['CPU_model'] = df['Cpu'].apply(extract_cpu_model)
df['CPU_model'] = df['CPU_model'].map(cpu_order)

In [26]:
df.drop('Cpu', axis=1, inplace=True)

In [27]:
df.head()

,id,Company,TypeName,Inches,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Touchscreen,IPS,Total_pixels,CPU_GHz,CPU_brand,CPU_model
0,697,2,0,12.5,4,64GB Flash Storage,Intel HD Graphics 515,0,1.20,669.0,1,0,2073600,0.9,1,10
1,435,2,1,17.3,8,256GB SSD + 1TB HDD,AMD Radeon RX 580,3,3.20,1695.0,0,0,2073600,3.2,0,15
2,735,10,3,15.6,4,1TB HDD,Intel HD Graphics 620,3,1.85,779.0,0,0,2073600,2.7,1,13
3,864,4,4,13.3,16,512GB SSD,Intel Iris Plus Graphics 640,3,1.29,2240.0,1,0,5760000,2.5,1,13
4,1176,10,3,15.6,4,1.0TB Hybrid,Intel HD Graphics 520,3,2.32,825.0,0,0,2073600,2.5,1,13

In [28]:
df["Memory"].unique() # sdd es más importante y caro que hdd

<StringArray>
[           '64GB Flash Storage',          '256GB SSD +  1TB HDD',
                       '1TB HDD',                     '512GB SSD',
                  '1.0TB Hybrid',                      '32GB SSD',
                     '500GB HDD',                     '256GB SSD',
          '128GB SSD +  1TB HDD',                     '128GB SSD',
            '32GB Flash Storage',           '128GB Flash Storage',
                     '180GB SSD',          '512GB SSD +  1TB HDD',
            '16GB Flash Storage',           '512GB Flash Storage',
                       '2TB HDD',          '256GB SSD +  2TB HDD',
        '512GB SSD +  256GB SSD',                       '1TB SSD',
        '256GB SSD +  256GB SSD',                  '508GB Hybrid',
           '256GB Flash Storage',                     '128GB HDD',
     '256GB SSD +  1.0TB Hybrid',        '512GB SSD +  512GB SSD',
          '128GB SSD +  2TB HDD', '64GB Flash Storage +  1TB HDD',
          '512GB SSD +  2TB HDD',                      '64GB SSD',
                     '240GB SSD',            '1TB HDD +  1TB HDD',
            '1TB SSD +  1TB HDD',        '256GB SSD +  500GB HDD',
                      '32GB HDD',                       '8GB SSD']
Length: 36, dtype: str

In [29]:
# separar tres columnas: SSD, HDD, Hybrid

def extract_storage(memory):
    ssd = 0
    hdd = 0
    hybrid = 0
    parts = memory.split('+')  # divide por '+' por si hay dos almacenamientos: ['256GB SSD', '1TB HDD']
    for part in parts:
        part = part.strip()  # quita espacios en blanco sobrantes
        
        # extrae el número en GB
        if 'TB' in part:
            size = int(float(part.split('TB')[0].strip()) * 1024)  # convierte TB a GB: 1TB → 1024GB
        else:
            size = int(float(part.split('GB')[0].strip()))  # ya está en GB: 256GB → 256
        
        # clasifica en SSD, HDD o Hybrid según las palabras clave
        if any(x in part for x in ['SSD', 'Flash']):
            ssd += size      # += acumula por si hay varios SSD: 512GB SSD + 256GB SSD → 768GB
        elif 'HDD' in part:
            hdd += size      # += acumula por si hay varios HDD: 1TB HDD + 1TB HDD → 2048GB
        elif 'Hybrid' in part:
            hybrid += size   # += acumula por si hay varios Hybrid

    return pd.Series([ssd, hdd, hybrid])  # devuelve los 3 valores a la vez

# asigna los 3 valores directamente a 3 columnas nuevas
df[['SSD_GB', 'HDD_GB', 'Hybrid_GB']] = df['Memory'].apply(extract_storage)
df.drop('Memory', axis=1, inplace=True)  # elimina la columna original ya que no la necesitamos

In [30]:
df.head()

,id,Company,TypeName,Inches,Ram,Gpu,OpSys,Weight,Price_euros,Touchscreen,IPS,Total_pixels,CPU_GHz,CPU_brand,CPU_model,SSD_GB,HDD_GB,Hybrid_GB
0,697,2,0,12.5,4,Intel HD Graphics 515,0,1.20,669.0,1,0,2073600,0.9,1,10,64,0,0
1,435,2,1,17.3,8,AMD Radeon RX 580,3,3.20,1695.0,0,0,2073600,3.2,0,15,256,1024,0
2,735,10,3,15.6,4,Intel HD Graphics 620,3,1.85,779.0,0,0,2073600,2.7,1,13,0,1024,0
3,864,4,4,13.3,16,Intel Iris Plus Graphics 640,3,1.29,2240.0,1,0,5760000,2.5,1,13,512,0,0
4,1176,10,3,15.6,4,Intel HD Graphics 520,3,2.32,825.0,0,0,2073600,2.5,1,13,0,0,1024

In [31]:
df["Gpu"].unique() # numero cuanto mas gordo mejor
# marcas importantes: Nvidia (más cara)

<StringArray>
[         'Intel HD Graphics 515',              'AMD Radeon RX 580',
          'Intel HD Graphics 620',   'Intel Iris Plus Graphics 640',
          'Intel HD Graphics 520',          'Intel HD Graphics 500',
          'Intel HD Graphics 505',        'Nvidia GeForce GTX 1060',
        'Nvidia GeForce GT 940MX',        'Nvidia GeForce GTX 1070',
     'Nvidia GeForce GTX 1050 Ti',                 'AMD Radeon 520',
          'Nvidia GeForce 930MX ',          'Intel HD Graphics 510',
                 'AMD Radeon 530',              'AMD Radeon RX 540',
             'AMD Radeon R5 M430',                 'AMD R17M-M1-70',
                  'AMD Radeon R2',          'Intel HD Graphics 400',
      'Nvidia GeForce GTX 1050Ti',        'Nvidia GeForce GTX 1050',
            'Nvidia Quadro M520M',           'Nvidia GeForce 930MX',
         'Intel UHD Graphics 620',         'Intel HD Graphics 6000',
           'Nvidia GeForce 940MX',             'AMD Radeon R7 M440',
                  'AMD Radeon R7',        'Nvidia GeForce GTX 980M',
             'AMD Radeon R5 M330',          'Intel HD Graphics 540',
        'Nvidia GeForce GTX 950M',         'Nvidia GeForce GTX1080',
   'Intel Iris Plus Graphics 650',             'AMD Radeon R7 M445',
        'Nvidia GeForce GTX 1080',              'Intel HD Graphics',
       'Nvidia GeForce GTX 1050M',           'Nvidia Quadro M1000M',
            'Nvidia Quadro M1200',           'Nvidia GeForce MX150',
                  'AMD Radeon R5',         'Intel HD Graphics 5300',
            'Nvidia Quadro M2200',          'Intel HD Graphics 615',
           'Nvidia GeForce 920MX',                  'AMD Radeon R4',
            'AMD Radeon R5 M420X',             'AMD Radeon R5 M420',
           'Nvidia GeForce MX130',            'Nvidia Quadro M620M',
             'Nvidia GTX 980 SLI',         'Nvidia GeForce GTX1060',
        'Nvidia GeForce GTX 960M',             'Nvidia Quadro M620',
          'Nvidia GeForce 920MX ',           'Nvidia GeForce 150MX',
            'Nvidia GeForce 930M',            'Nvidia GeForce 960M',
                 'AMD Radeon 540',         'Intel HD Graphics 620 ',
            'Nvidia GeForce 920M',              'AMD Radeon RX 550',
                  'AMD Radeon R3',         'AMD Radeon R2 Graphics',
        'Intel Iris Pro Graphics',        'Intel Iris Graphics 550',
             'Intel Graphics 620',       'Nvidia GeForce GTX 940MX',
         'AMD Radeon R4 Graphics',          'Intel HD Graphics 630',
             'AMD Radeon R5 M315',           'Nvidia Quadro M2200M',
 'Nvidia GeForce GTX 960<U+039C>',             'AMD Radeon R7 M460',
            'Nvidia Quadro M500M',      'Nvidia GeForce GTX1050 Ti',
              'AMD Radeon R5 520',        'Nvidia GeForce GTX 965M',
        'Intel Iris Graphics 540',          'Intel HD Graphics 405',
            'Nvidia Quadro 3000M',        'Nvidia GeForce GTX 970M',
            'AMD FirePro W4190M ',           'Nvidia Quadro M3000M',
             'AMD FirePro W6150M',        'Nvidia GeForce GTX 980 ',
           'Nvidia Quadro M2000M',             'AMD Radeon Pro 555',
         'Nvidia GeForce GTX 960',             'AMD FirePro W4190M',
             'AMD Radeon Pro 560',              'AMD Radeon R5 430']
Length: 94, dtype: str

In [32]:
import re

def extract_gpu_numbers(gpu):
    intel = 0
    amd = 0
    nvidia = 0  # iniciamos las 3 columnas a 0, si no tiene esa marca se queda en 0
    
    # extraer el primer número que aparece en el string
    number = re.search(r'(\d+)', gpu)  # busca el primer número en el string: 'GTX 1080' → 1080
    if number:
        number = int(number.group(1))  # lo convierte a int: '1080' → 1080
    else:
        number = 0  # si no hay número (ej: 'Intel HD Graphics') → 0
    
    # asigna el número a la columna de su marca, las otras se quedan en 0
    if 'Intel' in gpu:
        intel = number
    elif 'AMD' in gpu:
        amd = number
    elif 'Nvidia' in gpu:
        nvidia = number
    
    return pd.Series([intel, amd, nvidia])  # devuelve los 3 valores a la vez

# asigna los 3 valores directamente a 3 columnas nuevas
df[['GPU_Intel', 'GPU_AMD', 'GPU_Nvidia']] = df['Gpu'].apply(extract_gpu_numbers)
df.drop('Gpu', axis=1, inplace=True)  # elimina la columna original ya que no la necesitamos

In [33]:
df.head()

,id,Company,TypeName,Inches,Ram,OpSys,Weight,Price_euros,Touchscreen,IPS,Total_pixels,CPU_GHz,CPU_brand,CPU_model,SSD_GB,HDD_GB,Hybrid_GB,GPU_Intel,GPU_AMD,GPU_Nvidia
0,697,2,0,12.5,4,0,1.20,669.0,1,0,2073600,0.9,1,10,64,0,0,515,0,0
1,435,2,1,17.3,8,3,3.20,1695.0,0,0,2073600,3.2,0,15,256,1024,0,0,580,0
2,735,10,3,15.6,4,3,1.85,779.0,0,0,2073600,2.7,1,13,0,1024,0,620,0,0
3,864,4,4,13.3,16,3,1.29,2240.0,1,0,5760000,2.5,1,13,512,0,0,640,0,0
4,1176,10,3,15.6,4,3,2.32,825.0,0,0,2073600,2.5,1,13,0,0,1024,520,0,0

In [35]:
df.to_csv('train_limpio.csv', index=False)