# KAGGLE 1: MACHINE LEARNING ORDENADORES

### LIMPIEZA DE DATOS

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"test.csv")

In [3]:
df.head()

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
0,824,833,Lenovo,ThinkPad X1,Ultrabook,14.0,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB Flash Storage,Intel HD Graphics 620,Windows 10,1.13kg
1,101,104,HP,15-bw000nv (E2-9000e/4GB/500GB/Radeon,Notebook,15.6,Full HD 1920x1080,AMD E-Series E2-9000e 1.5GHz,4GB,500GB HDD,AMD Radeon R2,Windows 10,2.1kg
2,1157,1175,Lenovo,ThinkPad T460s,Ultrabook,14.0,Full HD 1920x1080,Intel Core i7 6600U 2.6GHz,12GB,512GB SSD,Intel HD Graphics 520,Windows 7,1.4kg
3,940,954,HP,Omen 17-W006na,Gaming,17.3,IPS Panel Full HD 1920x1080,Intel Core i5 6300HQ 2.3GHz,8GB,128GB SSD + 1TB HDD,Nvidia GeForce GTX 965M,Windows 10,2.75kg
4,853,864,Lenovo,ThinkPad T470p,Ultrabook,14.0,IPS Panel Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,8GB,256GB SSD,Nvidia GeForce GT 940MX,Windows 10,1.96kg

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                391 non-null    int64
 1   laptop_ID         391 non-null    int64
 2   Company           391 non-null    str
 3   Product           391 non-null    str
 4   TypeName          391 non-null    str
 5   Inches            391 non-null    float64
 6   ScreenResolution  391 non-null    str
 7   Cpu               391 non-null    str
 8   Ram               391 non-null    str
 9   Memory            391 non-null    str
 10  Gpu               391 non-null    str
 11  OpSys             391 non-null    str
 12  Weight            391 non-null    str
dtypes: float64(1), int64(2), str(10)
memory usage: 39.8 KB

### LIMPIEZA DE DATOS

Dropear laptop_ID:

In [5]:
df.drop(["laptop_ID"], axis=1, inplace=True)

Limpio Ram y Weight para quitar GB y kg, pasándolas a int y float respectivamente

In [6]:
df['Ram'] = df['Ram'].str.replace('GB', '').astype(int)

df['Weight'] = df['Weight'].str.replace('kg', '').astype(float)

Paso company a números con LabelEncoder

In [7]:
df["Company"].unique()

<StringArray>
[   'Lenovo',        'HP',      'Asus',      'Dell',       'MSI',      'Acer',
      'Vero',   'Toshiba',    'Google',   'Samsung',     'Razer',     'Chuwi',
    'Xiaomi',   'Fujitsu',     'Apple', 'Microsoft',        'LG',  'Mediacom']
Length: 18, dtype: str

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Company'] = le.fit_transform(df['Company'])

In [9]:
dict(zip(le.classes_, le.transform(le.classes_)))

{'Acer': np.int64(0),
 'Apple': np.int64(1),
 'Asus': np.int64(2),
 'Chuwi': np.int64(3),
 'Dell': np.int64(4),
 'Fujitsu': np.int64(5),
 'Google': np.int64(6),
 'HP': np.int64(7),
 'LG': np.int64(8),
 'Lenovo': np.int64(9),
 'MSI': np.int64(10),
 'Mediacom': np.int64(11),
 'Microsoft': np.int64(12),
 'Razer': np.int64(13),
 'Samsung': np.int64(14),
 'Toshiba': np.int64(15),
 'Vero': np.int64(16),
 'Xiaomi': np.int64(17)}

In [10]:
df.head()

,id,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
0,824,9,ThinkPad X1,Ultrabook,14.0,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB Flash Storage,Intel HD Graphics 620,Windows 10,1.13
1,101,7,15-bw000nv (E2-9000e/4GB/500GB/Radeon,Notebook,15.6,Full HD 1920x1080,AMD E-Series E2-9000e 1.5GHz,4,500GB HDD,AMD Radeon R2,Windows 10,2.10
2,1157,9,ThinkPad T460s,Ultrabook,14.0,Full HD 1920x1080,Intel Core i7 6600U 2.6GHz,12,512GB SSD,Intel HD Graphics 520,Windows 7,1.40
3,940,7,Omen 17-W006na,Gaming,17.3,IPS Panel Full HD 1920x1080,Intel Core i5 6300HQ 2.3GHz,8,128GB SSD + 1TB HDD,Nvidia GeForce GTX 965M,Windows 10,2.75
4,853,9,ThinkPad T470p,Ultrabook,14.0,IPS Panel Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,8,256GB SSD,Nvidia GeForce GT 940MX,Windows 10,1.96

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                391 non-null    int64
 1   Company           391 non-null    int64
 2   Product           391 non-null    str
 3   TypeName          391 non-null    str
 4   Inches            391 non-null    float64
 5   ScreenResolution  391 non-null    str
 6   Cpu               391 non-null    str
 7   Ram               391 non-null    int64
 8   Memory            391 non-null    str
 9   Gpu               391 non-null    str
 10  OpSys             391 non-null    str
 11  Weight            391 non-null    float64
dtypes: float64(2), int64(3), str(7)
memory usage: 36.8 KB

In [12]:
df["OpSys"].unique()

<StringArray>
[  'Windows 10',    'Windows 7',    'Chrome OS',        'No OS',
        'Linux',     'Mac OS X', 'Windows 10 S',        'macOS']
Length: 8, dtype: str

In [13]:
df['OpSys'].value_counts()

OpSys
Windows 10      327
No OS            20
Linux            16
Windows 7        12
Chrome OS         9
Windows 10 S      3
Mac OS X          2
macOS             2
Name: count, dtype: int64

In [14]:
# junto todos los windows, junto todos los mac y elimino android (son solo 2 datos)
df = df[df["OpSys"] != "Android"]

df["OpSys"] = df["OpSys"].replace({
    'Mac OS X': 'macOS',
    'Windows 10 S': 'Windows',
    'Windows 10': 'Windows',
    'Windows 7': 'Windows',
})

df["OpSys"] = le.fit_transform(df["OpSys"])

In [15]:
dict(zip(le.classes_, le.transform(le.classes_)))

{'Chrome OS': np.int64(0),
 'Linux': np.int64(1),
 'No OS': np.int64(2),
 'Windows': np.int64(3),
 'macOS': np.int64(4)}

TypeName tiene solo 6 entradas, así que las paso con labelencoder:

In [16]:
df["TypeName"].value_counts()

TypeName
Notebook              211
Ultrabook              66
Gaming                 62
2 in 1 Convertible     37
Netbook                 8
Workstation             7
Name: count, dtype: int64

In [17]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['TypeName'] = le.fit_transform(df['TypeName'])

In [18]:
dict(zip(le.classes_, le.transform(le.classes_)))

{'2 in 1 Convertible': np.int64(0),
 'Gaming': np.int64(1),
 'Netbook': np.int64(2),
 'Notebook': np.int64(3),
 'Ultrabook': np.int64(4),
 'Workstation': np.int64(5)}

Elimino la columna "product" porque contiene información que tienen otras columnas y tampoco me parece relevant el nombre del producto para el precio, sino sus características

In [19]:
df.drop(["Product"], axis=1, inplace=True)

Voy a ver qué hacer con las últimas 4:

In [20]:
df["ScreenResolution"].unique()

<StringArray>
[                  'IPS Panel Full HD 1920x1080',
                             'Full HD 1920x1080',
                                      '1366x768',
    'IPS Panel Quad HD+ / Touchscreen 3200x1800',
              'Quad HD+ / Touchscreen 3200x1800',
                                     '1920x1080',
               'Full HD / Touchscreen 1920x1080',
                         'Touchscreen 2560x1440',
 'IPS Panel Touchscreen / 4K Ultra HD 3840x2160',
                         'Touchscreen 2400x1600',
     'IPS Panel Full HD / Touchscreen 1920x1080',
                          'Touchscreen 1366x768',
 'IPS Panel 4K Ultra HD / Touchscreen 3840x2160',
           '4K Ultra HD / Touchscreen 3840x2160',
                                      '1600x900',
           'Touchscreen / 4K Ultra HD 3840x2160',
                  'IPS Panel Quad HD+ 2560x1440',
                         '4K Ultra HD 3840x2160',
               'IPS Panel Touchscreen 1920x1200',
               'IPS Panel 4K Ultra HD 3840x2160',
            'IPS Panel Retina Display 2304x1440',
                                     '2560x1440',
                         'Touchscreen 2256x1504',
               'IPS Panel Touchscreen 2560x1440',
                            'IPS Panel 1366x768',
                    'IPS Panel Full HD 1366x768',
               'IPS Panel Touchscreen 2400x1600',
            'IPS Panel Retina Display 2880x1800',
                                      '1440x900']
Length: 29, dtype: str

In [21]:
# Touchscreen: 1 si tiene, 0 si no (que la pantalla sea táctil)
df['Touchscreen'] = df['ScreenResolution'].str.contains('Touchscreen').astype(int)

# IPS Panel: 1 si tiene, 0 si no (IPS más caro, temas de color y ángulos de la pantalla)
df['IPS'] = df['ScreenResolution'].str.contains('IPS').astype(int)

# Resolución: extraer solo los píxeles
df['Resolution'] = df['ScreenResolution'].str.extract(r'(\d+x\d+)')

In [22]:
# calcular píxeles totales (anchoXalto); así el modelo entiendo que a más píxeles, más caro
df['Total_pixels'] = df['Resolution'].apply(lambda x: int(x.split('x')[0]) * int(x.split('x')[1]))

df.drop(['ScreenResolution', 'Resolution'], axis=1, inplace=True)

In [23]:
df["Cpu"].unique()

<StringArray>
[           'Intel Core i5 7200U 2.5GHz',
          'AMD E-Series E2-9000e 1.5GHz',
            'Intel Core i7 6600U 2.6GHz',
           'Intel Core i5 6300HQ 2.3GHz',
           'Intel Core i7 7700HQ 2.8GHz',
           'Intel Core i7 6820HK 2.7GHz',
  'Intel Celeron Dual Core 3855U 1.6GHz',
            'Intel Core i7 8550U 1.8GHz',
            'Intel Core i7 7500U 2.7GHz',
            'Intel Core i5 8250U 1.6GHz',
                   'AMD Ryzen 1700 3GHz',
             'AMD A6-Series 9220 2.5GHz',
            'Intel Core i7 6560U 2.2GHz',
            'Intel Core i3 6100U 2.3GHz',
  'Intel Celeron Dual Core 3205U 1.5GHz',
 'Intel Celeron Dual Core N3060 1.60GHz',
  'Intel Celeron Dual Core N3350 1.1GHz',
            'Intel Core i7 6500U 2.5GHz',
           'Intel Core i5 7300HQ 2.5GHz',
            'Intel Core i5 6200U 2.3GHz',
           'Intel Core i7 6700HQ 2.6GHz',
             'Intel Core i5 7Y57 1.2GHz',
            'Intel Core i3 7100U 2.4GHz',
            'Intel Core i5 7500U 2.7GHz',
  'Intel Celeron Dual Core N3060 1.6GHz',
            'Intel Core i7 7600U 2.8GHz',
             'Intel Core i7 7Y75 1.3GHz',
           'Intel Core i7 6500U 2.50GHz',
            'Intel Core i3 7130U 2.7GHz',
             'AMD A9-Series 9410 2.9GHz',
  'Intel Pentium Quad Core N3710 1.6GHz',
              'Intel Core i3 6006U 2GHz',
           'Intel Core i7 7820HK 2.9GHz',
              'Intel Core M 6Y30 0.9GHz',
  'Intel Celeron Dual Core N3050 1.6GHz',
           'AMD A12-Series 9720P 2.7GHz',
           'Intel Atom x5-Z8350 1.44GHz',
           'Intel Atom X5-Z8350 1.44GHz',
  'Intel Pentium Quad Core N4200 1.1GHz',
              'Intel Core M 7Y30 1.0GHz',
           'Intel Core i7 7820HQ 2.9GHz',
           'Intel Atom x5-Z8300 1.44GHz',
           'Intel Core i5 6440HQ 2.6GHz',
           'Intel Core i7 6820HQ 2.7GHz',
            'Intel Core i5 7300U 2.6GHz',
           'Intel Core i5 7440HQ 2.8GHz',
            'Intel Core i3 6006U 2.0GHz',
            'Intel Core i5 6300U 2.4GHz',
           'Intel Atom x5-Z8550 1.44GHz',
           'AMD A12-Series 9700P 2.5GHz',
                   'Intel Core M 1.1GHz',
               'AMD A9-Series 9420 3GHz',
           'Intel Core M m3-7Y30 2.2GHz',
  'Intel Pentium Quad Core N3700 1.6GHz',
       'AMD A10-Series A10-9620P 2.5GHz',
           'AMD A10-Series 9620P 2.5GHz',
              'Intel Core M 6Y75 1.2GHz',
                     'AMD FX 9830P 3GHz',
         'Samsung Cortex A72&A53 2.0GHz',
                  'Intel Core i7 2.7GHz',
              'Intel Core M 6Y54 1.1GHz',
                  'Intel Core i5 1.8GHz',
                   'AMD FX 8800P 2.1GHz',
           'AMD A10-Series 9600P 2.4GHz']
Length: 64, dtype: str

In [24]:
# Velocidad en GHz
df['CPU_GHz'] = df['Cpu'].str.extract(r'(\d+\.?\d*)GHz').astype(float)

# Marca: Intel (1) o AMD (0) 
df['CPU_brand'] = df['Cpu'].apply(lambda x: x.split()[0]) # coge si es AMD o Intel (primera palabra)
df['CPU_brand'] = le.fit_transform(df['CPU_brand']) # aquí aplica 0 a AMD y 1 a Intel

In [25]:
# diccionario de número ascendente por categoría de procesador
cpu_order = {
    # Intel gama baja
    'Atom': 0, 'Celeron': 1, 'Pentium': 2,
    # AMD gama baja
    'E-Series': 3, 'A4-Series': 4, 'A6-Series': 5, 'A8-Series': 6,
    'A9-Series': 7, 'A10-Series': 8, 'A12-Series': 9,
    # Intel gama media-alta
    'Core M': 10, 'Core i3': 11, 'Core i5': 12, 'Core i7': 13,
    # Gama profesional/alta
    'Xeon': 14, 'Ryzen': 15
    }

# establecer los números a cada categoría

def extract_cpu_model(cpu):
    parts = cpu.split()
    # Intel Core i5/i7/i3/M necesita 2 palabras
    if parts[1] == 'Core':
        return parts[1] + ' ' + parts[2]
    # resto con 1 palabra
    return parts[1]

df['CPU_model'] = df['Cpu'].apply(extract_cpu_model)
df['CPU_model'] = df['CPU_model'].map(cpu_order)

# Ver qué CPUs no están en el diccionario
print("CPUs sin mapear:", df[df['CPU_model'].isnull()]['Cpu'].unique())

# Rellenar nulos con la mediana
df['CPU_model'] = df['CPU_model'].fillna(df['CPU_model'].median())

CPUs sin mapear: <StringArray>
['AMD FX 9830P 3GHz', 'Samsung Cortex A72&A53 2.0GHz', 'AMD FX 8800P 2.1GHz']
Length: 3, dtype: str

In [26]:
df.drop('Cpu', axis=1, inplace=True)

In [27]:
df.head()

,id,Company,TypeName,Inches,Ram,Memory,Gpu,OpSys,Weight,Touchscreen,IPS,Total_pixels,CPU_GHz,CPU_brand,CPU_model
0,824,9,4,14.0,8,256GB Flash Storage,Intel HD Graphics 620,3,1.13,0,1,2073600,2.5,1,12.0
1,101,7,3,15.6,4,500GB HDD,AMD Radeon R2,3,2.10,0,0,2073600,1.5,0,3.0
2,1157,9,4,14.0,12,512GB SSD,Intel HD Graphics 520,3,1.40,0,0,2073600,2.6,1,13.0
3,940,7,1,17.3,8,128GB SSD + 1TB HDD,Nvidia GeForce GTX 965M,3,2.75,0,1,2073600,2.3,1,12.0
4,853,9,4,14.0,8,256GB SSD,Nvidia GeForce GT 940MX,3,1.96,0,1,2073600,2.8,1,13.0

In [28]:
df["Memory"].unique() # sdd es más importante y caro que hdd

<StringArray>
[      '256GB Flash Storage',                 '500GB HDD',
                 '512GB SSD',      '128GB SSD +  1TB HDD',
                 '256GB SSD',        '16GB Flash Storage',
      '256GB SSD +  1TB HDD',                   '1TB SSD',
                   '1TB HDD',                  '16GB SSD',
        '32GB Flash Storage',                 '180GB SSD',
                   '2TB HDD',                 '128GB SSD',
      '512GB SSD +  1TB HDD',              '1.0TB Hybrid',
        '1TB SSD +  1TB HDD',        '64GB Flash Storage',
      '256GB SSD +  2TB HDD',       '128GB Flash Storage',
                 '1.0TB HDD',      '128GB SSD +  2TB HDD',
 '512GB SSD +  1.0TB Hybrid']
Length: 23, dtype: str

In [29]:
# separar tres columnas: SSD, HDD, Hybrid

def extract_storage(memory):
    ssd = 0
    hdd = 0
    hybrid = 0
    parts = memory.split('+')  # divide por '+' por si hay dos almacenamientos: ['256GB SSD', '1TB HDD']
    for part in parts:
        part = part.strip()  # quita espacios en blanco sobrantes
        
        # extrae el número en GB
        if 'TB' in part:
            size = int(float(part.split('TB')[0].strip()) * 1024)  # convierte TB a GB: 1TB → 1024GB
        else:
            size = int(float(part.split('GB')[0].strip()))  # ya está en GB: 256GB → 256
        
        # clasifica en SSD, HDD o Hybrid según las palabras clave
        if any(x in part for x in ['SSD', 'Flash']):
            ssd += size      # += acumula por si hay varios SSD: 512GB SSD + 256GB SSD → 768GB
        elif 'HDD' in part:
            hdd += size      # += acumula por si hay varios HDD: 1TB HDD + 1TB HDD → 2048GB
        elif 'Hybrid' in part:
            hybrid += size   # += acumula por si hay varios Hybrid

    return pd.Series([ssd, hdd, hybrid])  # devuelve los 3 valores a la vez

# asigna los 3 valores directamente a 3 columnas nuevas
df[['SSD_GB', 'HDD_GB', 'Hybrid_GB']] = df['Memory'].apply(extract_storage)
df.drop('Memory', axis=1, inplace=True)  # elimina la columna original ya que no la necesitamos

In [30]:
df.head()

,id,Company,TypeName,Inches,Ram,Gpu,OpSys,Weight,Touchscreen,IPS,Total_pixels,CPU_GHz,CPU_brand,CPU_model,SSD_GB,HDD_GB,Hybrid_GB
0,824,9,4,14.0,8,Intel HD Graphics 620,3,1.13,0,1,2073600,2.5,1,12.0,256,0,0
1,101,7,3,15.6,4,AMD Radeon R2,3,2.10,0,0,2073600,1.5,0,3.0,0,500,0
2,1157,9,4,14.0,12,Intel HD Graphics 520,3,1.40,0,0,2073600,2.6,1,13.0,512,0,0
3,940,7,1,17.3,8,Nvidia GeForce GTX 965M,3,2.75,0,1,2073600,2.3,1,12.0,128,1024,0
4,853,9,4,14.0,8,Nvidia GeForce GT 940MX,3,1.96,0,1,2073600,2.8,1,13.0,256,0,0

In [31]:
df["Gpu"].unique() # numero cuanto mas gordo mejor
# marcas importantes: Nvidia (más cara)

<StringArray>
[         'Intel HD Graphics 620',                  'AMD Radeon R2',
          'Intel HD Graphics 520',        'Nvidia GeForce GTX 965M',
        'Nvidia GeForce GT 940MX',        'Nvidia GeForce GTX 1080',
          'Intel HD Graphics 510',           'Nvidia GeForce 930MX',
     'Nvidia GeForce GTX 1050 Ti',                 'AMD Radeon 530',
              'AMD Radeon RX 580',         'AMD Radeon R4 Graphics',
        'Nvidia GeForce GTX 1060',        'Intel Iris Graphics 540',
        'Nvidia GeForce GTX 1050',              'Intel HD Graphics',
           'Nvidia GeForce 940MX',          'Intel HD Graphics 400',
          'Intel HD Graphics 500',            'Nvidia GeForce 930M',
        'Nvidia GeForce GTX 960M',          'Intel HD Graphics 615',
        'Nvidia GeForce GTX 980M',            'AMD Radeon R7 M365X',
             'AMD Radeon R5 M420',        'Nvidia GeForce GTX 1070',
         'Intel UHD Graphics 620',             'AMD Radeon R7 M445',
           'Nvidia GeForce MX130',         'Nvidia GeForce GTX 960',
             'AMD Radeon R7 M440',            'Nvidia GeForce 920M',
          'Intel HD Graphics 405',           'Nvidia GeForce MX150',
          'Intel HD Graphics 515',       'Nvidia GeForce GTX 1070M',
                 'AMD Radeon 520',            'Nvidia Quadro M1200',
          'Intel HD Graphics 505',             'AMD Radeon R7 M360',
             'Nvidia Quadro M620',                'AMD R4 Graphics',
             'AMD FirePro W5130M',          'Intel HD Graphics 630',
             'AMD Radeon R5 M330',          'Nvidia GeForce 930MX ',
           'Nvidia Quadro M2000M',             'AMD Radeon R7 M465',
           'Nvidia GeForce 920MX',         'AMD Radeon R7 Graphics',
          'Intel HD Graphics 530',         'Intel HD Graphics 5300',
             'Nvidia GeForce 920',                  'AMD Radeon R5',
              'AMD Radeon RX 550',        'Nvidia GeForce GTX 970M',
       'Nvidia GeForce GTX 1050M',            'Nvidia GeForce 940M',
       'Nvidia GeForce GTX 930MX',             'AMD Radeon R5 M430',
        'Nvidia GeForce GTX 940M',                  'AMD Radeon R4',
              'AMD Radeon RX 560',              'ARM Mali T860 MP4',
 'Nvidia GeForce GTX 960<U+039C>',             'AMD Radeon Pro 455',
         'Intel HD Graphics 6000',             'AMD Radeon R9 M385',
          'Nvidia GeForce 920MX ']
Length: 69, dtype: str

In [32]:
import re

def extract_gpu_numbers(gpu):
    intel = 0
    amd = 0
    nvidia = 0  # iniciamos las 3 columnas a 0, si no tiene esa marca se queda en 0
    
    # extraer el primer número que aparece en el string
    number = re.search(r'(\d+)', gpu)  # busca el primer número en el string: 'GTX 1080' → 1080
    if number:
        number = int(number.group(1))  # lo convierte a int: '1080' → 1080
    else:
        number = 0  # si no hay número (ej: 'Intel HD Graphics') → 0
    
    # asigna el número a la columna de su marca, las otras se quedan en 0
    if 'Intel' in gpu:
        intel = number
    elif 'AMD' in gpu:
        amd = number
    elif 'Nvidia' in gpu:
        nvidia = number
    
    return pd.Series([intel, amd, nvidia])  # devuelve los 3 valores a la vez

# asigna los 3 valores directamente a 3 columnas nuevas
df[['GPU_Intel', 'GPU_AMD', 'GPU_Nvidia']] = df['Gpu'].apply(extract_gpu_numbers)
df.drop('Gpu', axis=1, inplace=True)  # elimina la columna original ya que no la necesitamos

In [33]:
df.head()

,id,Company,TypeName,Inches,Ram,OpSys,Weight,Touchscreen,IPS,Total_pixels,CPU_GHz,CPU_brand,CPU_model,SSD_GB,HDD_GB,Hybrid_GB,GPU_Intel,GPU_AMD,GPU_Nvidia
0,824,9,4,14.0,8,3,1.13,0,1,2073600,2.5,1,12.0,256,0,0,620,0,0
1,101,7,3,15.6,4,3,2.10,0,0,2073600,1.5,0,3.0,0,500,0,0,2,0
2,1157,9,4,14.0,12,3,1.40,0,0,2073600,2.6,1,13.0,512,0,0,520,0,0
3,940,7,1,17.3,8,3,2.75,0,1,2073600,2.3,1,12.0,128,1024,0,0,0,965
4,853,9,4,14.0,8,3,1.96,0,1,2073600,2.8,1,13.0,256,0,0,0,0,940

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            391 non-null    int64
 1   Company       391 non-null    int64
 2   TypeName      391 non-null    int64
 3   Inches        391 non-null    float64
 4   Ram           391 non-null    int64
 5   OpSys         391 non-null    int64
 6   Weight        391 non-null    float64
 7   Touchscreen   391 non-null    int64
 8   IPS           391 non-null    int64
 9   Total_pixels  391 non-null    int64
 10  CPU_GHz       391 non-null    float64
 11  CPU_brand     391 non-null    int64
 12  CPU_model     391 non-null    float64
 13  SSD_GB        391 non-null    int64
 14  HDD_GB        391 non-null    int64
 15  Hybrid_GB     391 non-null    int64
 16  GPU_Intel     391 non-null    int64
 17  GPU_AMD       391 non-null    int64
 18  GPU_Nvidia    391 non-null    int64
dtypes: float64(4), int64(15)
memory usage: 58.2 KB

In [35]:
df.to_csv('test_limpio.csv', index=False)